import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        // Jakarta Properties (10)
        {
            name: "Luxurious Penthouse in SCBD",
            city: "Jakarta",
            area: "SCBD",
            type: "Penthouse",
            price: 4500000,
            nights: 2,
            rating: 4.9,
            imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
            isGuestFavorite: true,
            description: "Experience the epitome of urban luxury in this stunning penthouse located in Jakarta's prestigious SCBD district. This 300-square-meter masterpiece features floor-to-ceiling windows offering breathtaking panoramic views of the city skyline. The open-concept living space is elegantly furnished with designer pieces, complemented by a state-of-the-art kitchen equipped with premium appliances. The master suite boasts a private terrace, walk-in closet, and spa-like bathroom with a Jacuzzi. Two additional bedrooms provide ample space for guests or family. Residents enjoy exclusive access to building amenities including an infinity pool, fitness center, and 24-hour concierge service. Located steps away from luxury shopping, fine dining restaurants, and corporate offices, this penthouse offers the perfect blend of comfort and convenience for discerning travelers and business executives seeking an unforgettable Jakarta experience.",
            address: "Jl. Jenderal Sudirman Kav. 52-53",
            country: "Indonesia",
            latitude: -6.2253,
            longitude: 106.8089,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "Smart TV", "Full Kitchen", "Washer & Dryer", "City View", "Infinity Pool", "Gym Access", "Parking", "24/7 Security", "Concierge", "Elevator", "Work Desk", "Coffee Maker", "Wine Cooler"],
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: "Modern Apartment in Menteng",
            city: "Jakarta",
            area: "Menteng",
            type: "Apartment",
            price: 1200000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
            isGuestFavorite: false,
            description: "Discover the charm of historic Menteng in this beautifully appointed modern apartment. This 120-square-meter residence perfectly blends contemporary design with classic Indonesian elegance. The spacious living room features comfortable seating and a large flat-screen TV, ideal for relaxation after exploring the city. The fully equipped kitchen includes modern appliances and all necessary cookware for preparing meals. Both bedrooms are thoughtfully designed with plush bedding, ample storage, and blackout curtains ensuring restful sleep. The master bedroom includes an en-suite bathroom with a rainfall shower. Located in Jakarta's most prestigious neighborhood, you'll be surrounded by tree-lined streets, colonial architecture, and within walking distance to authentic Indonesian restaurants, cafes, and cultural attractions. Perfect for couples or small families seeking an authentic Jakarta experience with modern comforts.",
            address: "Jl. Teuku Umar No. 45",
            country: "Indonesia",
            latitude: -6.1944,
            longitude: 106.8229,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Kitchen", "Smart TV", "Washing Machine", "Iron", "Parking", "Security", "Elevator", "Work Space", "Coffee Maker", "Microwave"],
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: "Elegant Villa in Kemang",
            city: "Jakarta",
            area: "Kemang",
            type: "Villa",
            price: 3200000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
            isGuestFavorite: true,
            description: "Escape to this private sanctuary nestled in the heart of Kemang, Jakarta's trendiest neighborhood. This stunning 250-square-meter villa combines tropical elegance with modern luxury. The property features an open-plan living area with soaring ceilings, floor-to-ceiling glass doors leading to a lush private garden with a sparkling swimming pool. The master suite is a true retreat, complete with a king-size bed, private balcony, and luxurious bathroom with both bathtub and rain shower. Three additional bedrooms provide comfort and privacy for guests. The fully equipped kitchen opens to a covered outdoor dining area, perfect for entertaining. The villa's prime Kemang location puts you steps away from the area's best restaurants, bars, boutiques, and entertainment venues. With its tranquil ambiance and proximity to Jakarta's vibrant social scene, this villa offers the perfect balance for discerning travelers seeking both relaxation and excitement.",
            address: "Jl. Kemang Raya No. 78",
            country: "Indonesia",
            latitude: -6.2615,
            longitude: 106.8163,
            bedrooms: 4,
            bathrooms: 3,
            maxGuests: 8,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
                "https://images.unsplash.com/photo-1505577058444-a3dab90d4253"
            ],
            amenities: ["WiFi", "Air Conditioning", "Private Pool", "Garden", "Full Kitchen", "BBQ Grill", "Smart TV", "Washer & Dryer", "Parking", "Security", "Outdoor Dining", "Sun Loungers", "Work Desk", "Sound System", "Pet Friendly"],
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: "Boutique Hotel Suite in Thamrin",
            city: "Jakarta",
            area: "Thamrin",
            type: "Hotel",
            price: 950000,
            nights: 2,
            rating: 4.6,
            imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
            isGuestFavorite: false,
            description: "Immerse yourself in refined comfort at this boutique hotel suite located in the heart of Jakarta's business district. This elegantly designed 45-square-meter suite offers a sophisticated blend of contemporary style and functionality. The sleeping area features a plush king-size bed with premium linens, while the separate living space includes a comfortable sofa, work desk, and entertainment system. The marble bathroom is equipped with a rainfall shower and luxury toiletries. Guests enjoy access to hotel amenities including a rooftop pool with stunning city views, a well-equipped fitness center, and an on-site restaurant serving Indonesian and international cuisine. The hotel's central Thamrin location provides easy access to major shopping centers, corporate offices, and cultural attractions. Whether you're in Jakarta for business or pleasure, this suite offers the perfect home base with professional service and modern conveniences.",
            address: "Jl. M.H. Thamrin No. 89",
            country: "Indonesia",
            latitude: -6.1944,
            longitude: 106.8229,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["WiFi", "Air Conditioning", "TV", "Room Service", "Rooftop Pool", "Gym", "Restaurant", "Concierge", "Daily Housekeeping", "Work Desk", "Mini Bar", "Coffee Maker"],
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: "Contemporary House in Pondok Indah",
            city: "Jakarta",
            area: "Pondok Indah",
            type: "House",
            price: 1800000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
            isGuestFavorite: false,
            description: "Experience suburban tranquility in this beautifully maintained contemporary house located in the exclusive Pondok Indah neighborhood. This 180-square-meter residence features a bright, open-concept main floor with a modern living room, dining area, and fully equipped kitchen with an island breakfast bar. The living spaces are flooded with natural light from large windows overlooking a manicured garden. Three comfortable bedrooms upstairs provide restful retreats, with the master suite offering an en-suite bathroom and walk-in closet. A fourth bedroom on the ground floor can serve as a guest room or home office. The backyard includes a covered terrace perfect for outdoor dining and relaxation. Located in one of Jakarta's most desirable residential areas, you'll enjoy proximity to Pondok Indah Mall, international schools, golf courses, and numerous dining options. This house is ideal for families or groups seeking a peaceful retreat with easy access to city amenities.",
            address: "Jl. Metro Pondok Indah No. 34",
            country: "Indonesia",
            latitude: -6.2655,
            longitude: 106.7831,
            bedrooms: 4,
            bathrooms: 3,
            maxGuests: 8,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
                "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea",
                "https://images.unsplash.com/photo-1600607687644-c7171b42498f"
            ],
            amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Garden", "Parking", "Washer & Dryer", "Smart TV", "Work Desk", "Outdoor Seating", "Security", "BBQ Grill", "Dining Table", "Coffee Maker", "Pet Friendly"],
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: "Stylish Condo in Kuningan",
            city: "Jakarta",
            area: "Kuningan",
            type: "Condo",
            price: 1400000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
            isGuestFavorite: true,
            description: "Discover urban sophistication in this stylish condominium located in Jakarta's prestigious Kuningan business district. This 100-square-meter unit showcases modern interior design with clean lines, premium finishes, and thoughtful details throughout. The open living and dining area features contemporary furniture, a large smart TV, and expansive windows offering stunning city views. The gourmet kitchen is equipped with high-end appliances, granite countertops, and a breakfast bar. Two spacious bedrooms provide comfortable sleeping arrangements, with the master bedroom featuring an en-suite bathroom with a luxurious soaking tub. Residents enjoy access to world-class building amenities including a heated swimming pool, fully equipped gym, sauna, and 24-hour security. The location puts you within walking distance of major corporate offices, luxury hotels, and the vibrant Kuningan entertainment district. Perfect for business travelers and couples seeking a premium Jakarta experience.",
            address: "Jl. H.R. Rasuna Said Kav. C-22",
            country: "Indonesia",
            latitude: -6.2293,
            longitude: 106.8311,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "City View", "Swimming Pool", "Gym", "Kitchen", "Smart TV", "Washer & Dryer", "Parking", "24/7 Security", "Elevator", "Work Desk", "Coffee Maker", "Microwave"],
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: "Cozy Apartment in Senopati",
            city: "Jakarta",
            area: "Senopati",
            type: "Apartment",
            price: 850000,
            nights: 2,
            rating: 4.5,
            imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
            isGuestFavorite: false,
            description: "Experience the vibrant energy of Senopati from this charming apartment perfectly situated in Jakarta's hippest neighborhood. This 65-square-meter space has been thoughtfully designed to maximize comfort and functionality. The main living area combines the kitchen, dining, and lounging spaces in an inviting open layout. The bedroom features a comfortable queen-size bed and ample closet space, while the modern bathroom includes a glass-enclosed shower. Large windows throughout the apartment fill the space with natural light and offer glimpses of the bustling street life below. The building provides essential amenities including elevator access, security, and parking. What truly sets this apartment apart is its unbeatable location in the heart of Senopati, where you'll find yourself surrounded by Jakarta's most acclaimed restaurants, trendy bars, artisan cafes, and boutique shops. Whether you're a foodie, culture enthusiast, or young professional, this apartment offers the perfect base for exploring Jakarta's most dynamic neighborhood.",
            address: "Jl. Senopati No. 67",
            country: "Indonesia",
            latitude: -6.2368,
            longitude: 106.8101,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Kitchen", "TV", "Washer", "Elevator", "Parking", "Security", "Work Desk", "Coffee Maker", "Microwave", "Iron"],
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: "Executive Hotel Suite in Mega Kuningan",
            city: "Jakarta",
            area: "Mega Kuningan",
            type: "Hotel",
            price: 1100000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
            isGuestFavorite: false,
            description: "Elevate your Jakarta stay in this executive hotel suite located in the prestigious Mega Kuningan area. This 55-square-meter suite offers a sophisticated blend of business functionality and leisure comfort. The spacious bedroom features a king-size bed with premium bedding, blackout curtains, and a large smart TV. A separate sitting area provides a comfortable sofa, coffee table, and work desk with ergonomic chair, ideal for business travelers. The modern bathroom includes dual sinks, a walk-in shower, and luxury bath amenities. Suite guests enjoy exclusive access to the executive lounge with complimentary breakfast, afternoon tea, and evening cocktails. Additional hotel facilities include a stunning rooftop infinity pool, state-of-the-art fitness center, spa, and multiple dining options ranging from authentic Indonesian cuisine to international favorites. Located in the heart of Jakarta's Golden Triangle, you're surrounded by multinational corporations, luxury shopping, and fine dining establishments.",
            address: "Jl. Dr. Ide Anak Agung Gde Agung",
            country: "Indonesia",
            latitude: -6.2275,
            longitude: 106.8317,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "Smart TV", "Executive Lounge", "Infinity Pool", "Gym", "Spa", "Restaurant", "Room Service", "Work Desk", "Coffee Maker", "Mini Bar", "Concierge", "Valet Parking"],
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: "Spacious Villa in Pantai Indah Kapuk",
            city: "Jakarta",
            area: "Pantai Indah Kapuk",
            type: "Villa",
            price: 2800000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
            isGuestFavorite: true,
            description: "Discover waterfront luxury in this impressive villa located in Jakarta's exclusive Pantai Indah Kapuk development. This 280-square-meter property offers a perfect blend of indoor and outdoor living spaces. The grand entrance leads to an expansive open-plan living area with soaring ceilings, designer furnishings, and floor-to-ceiling windows overlooking a private pool and landscaped garden. The gourmet kitchen features top-of-the-line appliances, custom cabinetry, and an island perfect for entertaining. Four generously sized bedrooms, each with en-suite bathrooms, provide luxurious accommodation for up to 10 guests. The master suite includes a private balcony, walk-in closet, and spa-inspired bathroom with a jacuzzi tub. Outdoor amenities include a covered pavilion with dining area, poolside lounge chairs, and tropical gardens. The villa's location in PIK offers access to waterfront restaurants, shopping centers, and recreational facilities. Ideal for families, groups, or anyone seeking a private resort-style experience.",
            address: "Jl. Marina Indah Raya No. 12",
            country: "Indonesia",
            latitude: -6.1098,
            longitude: 106.7368,
            bedrooms: 4,
            bathrooms: 4,
            maxGuests: 10,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
                "https://images.unsplash.com/photo-1505577058444-a3dab90d4253"
            ],
            amenities: ["WiFi", "Air Conditioning", "Private Pool", "Garden", "Full Kitchen", "Smart TV", "Washer & Dryer", "Parking", "Security", "BBQ Area", "Outdoor Dining", "Sun Loungers", "Work Desk", "Sound System", "Pet Friendly"],
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: "Modern Loft in Kebayoran Baru",
            city: "Jakarta",
            area: "Kebayoran Baru",
            type: "Apartment",
            price: 750000,
            nights: 2,
            rating: 4.6,
            imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
            isGuestFavorite: false,
            description: "Experience contemporary urban living in this stylish loft apartment situated in the established Kebayoran Baru neighborhood. This 75-square-meter space features an open layout with high ceilings, exposed brick walls, and industrial-chic design elements. The living area flows seamlessly into a modern kitchen equipped with stainless steel appliances and a breakfast bar. The sleeping area, cleverly separated by a partial wall, offers privacy while maintaining the loft's open feel and includes a comfortable queen bed with quality linens. The bathroom showcases modern fixtures and a glass-enclosed rain shower. Large windows and a small balcony provide natural light and city views. The apartment building offers elevator access, security, and parking. Located in one of Jakarta's most established residential areas, you'll enjoy easy access to Blok M shopping center, authentic Indonesian eateries, international restaurants, and excellent public transportation connections.",
            address: "Jl. Wolter Monginsidi No. 88",
            country: "Indonesia",
            latitude: -6.2426,
            longitude: 106.7968,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Kitchen", "TV", "Washer", "Elevator", "Parking", "Security", "Work Desk", "Coffee Maker", "Balcony", "Iron"],
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },

        // Bandung Properties (5)
        {
            name: "Colonial Heritage Villa in Dago",
            city: "Bandung",
            area: "Dago",
            type: "Villa",
            price: 2200000,
            nights: 2,
            rating: 4.9,
            imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
            isGuestFavorite: true,
            description: "Step back in time at this beautifully restored colonial villa nestled in the hills of Dago, Bandung's most prestigious area. This 220-square-meter heritage property seamlessly blends historical charm with modern comfort. The villa features original hardwood floors, high ceilings with ornate moldings, and large windows that fill the space with natural light and showcase mountain views. The spacious living room showcases period furniture and a working fireplace, perfect for cool Bandung evenings. Three elegantly appointed bedrooms offer comfortable beds with premium linens, while the master suite includes a private sitting area and vintage bathtub. The modern kitchen is fully equipped yet maintains the property's historical character. Outside, terraced gardens with mature trees, flowering plants, and a stone patio provide a serene setting for outdoor dining and relaxation. Located minutes from Dago's famous culinary street and attractions like Dago Dream Park, this villa offers a unique combination of historical ambiance and convenient location.",
            address: "Jl. Dago Giri No. 156",
            country: "Indonesia",
            latitude: -6.8568,
            longitude: 107.6048,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"
            ],
            amenities: ["WiFi", "Air Conditioning", "Fireplace", "Full Kitchen", "Garden", "Mountain View", "Parking", "Washer & Dryer", "Outdoor Dining", "BBQ Grill", "Work Desk", "Coffee Maker", "Pet Friendly", "Historical Architecture"],
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            name: "Mountain View Apartment in Lembang",
            city: "Bandung",
            area: "Lembang",
            type: "Apartment",
            price: 680000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
            isGuestFavorite: false,
            description: "Escape to the cool mountain air of Lembang in this cozy apartment offering breathtaking views of the surrounding highlands. This 80-square-meter unit features a comfortable living area with large windows framing spectacular mountain vistas. The open-plan design connects the living space with a well-equipped kitchenette perfect for preparing simple meals. Two bedrooms provide comfortable sleeping arrangements with warm bedding ideal for the cooler climate. The apartment's location in Lembang puts you at the heart of Bandung's premier leisure destination, with easy access to numerous attractions including Floating Market, Farm House, and countless cafes and restaurants. The cool climate, fresh mountain air, and stunning natural surroundings make this the perfect retreat from tropical heat. Whether you're seeking outdoor adventures or simply want to relax and enjoy the mountain scenery, this apartment offers a comfortable and affordable base for your Bandung getaway.",
            address: "Jl. Raya Lembang No. 234",
            country: "Indonesia",
            latitude: -6.8116,
            longitude: 107.6178,
            bedrooms: 2,
            bathrooms: 1,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Heating", "Mountain View", "Kitchen", "TV", "Parking", "Security", "Balcony", "Coffee Maker", "Work Desk", "Hot Water", "Iron"],
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: "Boutique Hotel Room in Riau",
            city: "Bandung",
            area: "Riau",
            type: "Hotel",
            price: 580000,
            nights: 2,
            rating: 4.5,
            imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
            isGuestFavorite: false,
            description: "Experience Bandung's vibrant city center from this charming boutique hotel room located on the famous Riau Street. This 35-square-meter room features contemporary design with local artistic touches, including Indonesian artwork and handcrafted textiles. The comfortable sleeping area includes a queen-size bed with quality linens, while the compact yet functional bathroom offers modern amenities and a refreshing rain shower. Guests can enjoy hotel facilities including a rooftop cafe with city views, complimentary breakfast, and friendly 24-hour reception service. The hotel's prime Riau location puts you in the heart of Bandung's shopping and culinary district, with countless factory outlets, restaurants, and cafes within walking distance. Nearby attractions include Gedung Sate, Braga Street, and the famous Asian African Conference Museum. Perfect for solo travelers, couples, or business visitors seeking comfortable accommodation in the center of Bandung's action.",
            address: "Jl. Riau No. 45",
            country: "Indonesia",
            latitude: -6.9034,
            longitude: 107.6186,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["WiFi", "Air Conditioning", "TV", "Daily Housekeeping", "Breakfast Included", "Rooftop Cafe", "24hr Reception", "Work Desk", "Coffee Maker", "Hot Water", "City View"],
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: "Family House in Setiabudhi",
            city: "Bandung",
            area: "Setiabudhi",
            type: "House",
            price: 1350000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
            isGuestFavorite: true,
            description: "Create lasting family memories in this spacious house nestled in the serene Setiabudhi hills. This 160-square-meter property offers comfortable accommodation for families or groups seeking a peaceful Bandung retreat. The house features a large living room with comfortable seating and entertainment system, perfect for family gatherings. The dining area connects to a fully equipped kitchen with modern appliances and ample preparation space. Three bedrooms upstairs provide comfortable sleeping arrangements, with the master bedroom offering an en-suite bathroom and mountain views. A fourth room on the ground floor can serve as an additional bedroom or activity room for children. The backyard includes a covered terrace with outdoor furniture, ideal for enjoying Bandung's cool evenings. Located in the prestigious Setiabudhi area, you'll be close to attractions like Farmhouse Lembang, Dusun Bambu, and numerous restaurants. The house provides a home-away-from-home atmosphere with the privacy and space families need.",
            address: "Jl. Dr. Setiabudhi No. 212",
            country: "Indonesia",
            latitude: -6.8747,
            longitude: 107.5976,
            bedrooms: 4,
            bathrooms: 2,
            maxGuests: 8,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
                "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea",
                "https://images.unsplash.com/photo-1600607687644-c7171b42498f"
            ],
            amenities: ["WiFi", "Heating", "Full Kitchen", "Garden", "Mountain View", "Parking", "TV", "Washer", "Outdoor Seating", "BBQ Grill", "Work Desk", "Coffee Maker", "Dining Table", "Pet Friendly"],
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            name: "Urban Condo in Pasteur",
            city: "Bandung",
            area: "Pasteur",
            type: "Condo",
            price: 920000,
            nights: 2,
            rating: 4.6,
            imageUrl: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
            isGuestFavorite: false,
            description: "Discover modern convenience in this well-appointed condominium located in Bandung's growing Pasteur district. This 70-square-meter unit features a contemporary open-plan design with stylish furnishings and thoughtful amenities. The living area includes comfortable seating, a smart TV, and large windows offering city views. The kitchenette is equipped with essential appliances and dining space for four. Two bedrooms provide comfortable sleeping arrangements with quality bedding and ample storage. The modern bathroom features a walk-in shower with hot water. Residents enjoy building amenities including a swimming pool, fitness center, and secure parking. The condo's Pasteur location offers excellent access to Bandung's business district, shopping centers including Pasteur Hyper Square and 23 Paskal Shopping Center, and the toll road for easy trips to Jakarta or other cities. Whether you're in Bandung for business or leisure, this condo provides a comfortable urban base with modern conveniences.",
            address: "Jl. Dr. Djunjunan No. 168",
            country: "Indonesia",
            latitude: -6.8994,
            longitude: 107.5701,
            bedrooms: 2,
            bathrooms: 1,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af"
            ],
            amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Gym", "Kitchen", "TV", "Parking", "Security", "Elevator", "City View", "Work Desk", "Coffee Maker", "Hot Water"],
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },

        // Bali Properties (8)
        {
            name: "Beachfront Villa in Seminyak",
            city: "Bali",
            area: "Seminyak",
            type: "Villa",
            price: 5500000,
            nights: 2,
            rating: 5.0,
            imageUrl: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
            isGuestFavorite: true,
            description: "Experience ultimate luxury at this spectacular beachfront villa in the heart of Seminyak. This 400-square-meter masterpiece combines traditional Balinese architecture with contemporary design elements. The open-concept living pavilion features soaring alang-alang thatched roofs, polished terrazzo floors, and walls that open completely to the tropical gardens and private pool. The villa includes five beautifully appointed bedroom suites, each with en-suite bathrooms featuring rain showers and luxurious bathtubs. The master suite offers direct beach access and a private outdoor shower. A fully equipped modern kitchen, separate dining pavilion, and multiple lounging areas provide ample space for entertaining. The stunning infinity pool overlooks the beach, complemented by sun loungers, a poolside bar, and traditional bale. Full-time staff including a personal chef, butler, and housekeepers ensure an effortless stay. Steps from Seminyak's renowned beach clubs, restaurants, and boutiques, yet offering complete privacy, this villa defines tropical luxury living.",
            address: "Jl. Pantai Seminyak No. 17",
            country: "Indonesia",
            latitude: -8.6881,
            longitude: 115.1572,
            bedrooms: 5,
            bathrooms: 5,
            maxGuests: 10,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1540541338287-41700207dee6",
                "https://images.unsplash.com/photo-1582719508461-905c673771fd",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1505577058444-a3dab90d4253",
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4"
            ],
            amenities: ["WiFi", "Air Conditioning", "Private Pool", "Beach Access", "Ocean View", "Full Kitchen", "Personal Chef", "Butler Service", "Housekeeping", "Smart TV", "Sound System", "Outdoor Dining", "Sun Loungers", "Tropical Garden", "Beach Towels"],
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: "Luxury Penthouse in Nusa Dua",
            city: "Bali",
            area: "Nusa Dua",
            type: "Penthouse",
            price: 3800000,
            nights: 2,
            rating: 4.9,
            imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
            isGuestFavorite: true,
            description: "Indulge in sophisticated elegance at this stunning penthouse located within Nusa Dua's exclusive resort enclave. This 250-square-meter residence occupies the entire top floor, offering panoramic views of the Indian Ocean and tropical gardens. The spacious interior showcases contemporary design with Indonesian art pieces and custom furniture. Floor-to-ceiling windows and expansive terraces create a seamless indoor-outdoor living experience. Three luxurious bedrooms feature king-size beds, walk-in closets, and spa-like bathrooms with ocean-view soaking tubs. The gourmet kitchen is equipped with premium appliances and a wine cellar. The crowning jewel is the expansive rooftop terrace with an infinity pool, outdoor kitchen, dining area, and daybeds perfect for sunset viewing. Residents enjoy access to the resort's world-class amenities including a championship golf course, pristine beaches, multiple restaurants, and spa facilities. This penthouse offers the perfect combination of private luxury and resort conveniences.",
            address: "Kawasan Pariwisata Nusa Dua Lot 88",
            country: "Indonesia",
            latitude: -8.8009,
            longitude: 115.2305,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "Rooftop Pool", "Ocean View", "Full Kitchen", "Wine Cellar", "Smart TV", "Sound System", "Golf Course Access", "Beach Access", "Spa Access", "Concierge", "Parking", "Work Desk", "Premium Toiletries"],
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: "Traditional Villa in Ubud",
            city: "Bali",
            area: "Ubud",
            type: "Villa",
            price: 2400000,
            nights: 2,
            rating: 4.9,
            imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
            isGuestFavorite: true,
            description: "Immerse yourself in Balinese culture at this authentic traditional villa nestled in the heart of Ubud's rice terraces. This 180-square-meter property exemplifies classical Balinese architecture with its thatched roofs, carved wooden doors, and stone sculptures throughout. The main living pavilion opens to a private garden with a natural stone pool surrounded by tropical plantings and a traditional Balinese gazebo. Three beautifully appointed bedrooms feature carved wooden furniture, fine linens, and en-suite bathrooms with garden showers. The villa includes a fully equipped kitchen and outdoor dining area overlooking the rice fields. Daily housekeeping and a private cook are included, ready to prepare authentic Indonesian dishes using local ingredients. Located just minutes from Ubud's famous Monkey Forest, art galleries, yoga studios, and organic cafes, this villa offers a peaceful retreat while keeping Ubud's cultural attractions easily accessible. Perfect for those seeking an authentic Balinese experience.",
            address: "Jl. Raya Pengosekan No. 28",
            country: "Indonesia",
            latitude: -8.5069,
            longitude: 115.2625,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
                "https://images.unsplash.com/photo-1505577058444-a3dab90d4253"
            ],
            amenities: ["WiFi", "Air Conditioning", "Private Pool", "Rice Field View", "Full Kitchen", "Personal Cook", "Housekeeping", "Garden", "Traditional Architecture", "Outdoor Shower", "Dining Pavilion", "Yoga Deck", "Tropical Garden", "Cultural Experience"],
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: "Modern Apartment in Canggu",
            city: "Bali",
            area: "Canggu",
            type: "Apartment",
            price: 1100000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
            isGuestFavorite: false,
            description: "Experience Canggu's vibrant surf culture from this stylish modern apartment located in the heart of Bali's trendiest beach town. This 90-square-meter unit features an open-plan design with contemporary furnishings, polished concrete floors, and tropical accents. The living area flows onto a private balcony with views of the surrounding rice fields. The sleek kitchen is fully equipped with modern appliances perfect for preparing healthy meals with local ingredients from nearby markets. Two comfortable bedrooms include ample storage and quality bedding, while the master bedroom features an en-suite bathroom. The building offers a rooftop pool with ocean glimpses, gym facilities, and secure parking for scooters or cars. Located minutes from Canggu's famous surf breaks, beach clubs like Finns and The Lawn, countless cafes, yoga studios, and boutique shops. This apartment is perfect for digital nomads, surfers, and travelers seeking the ultimate Canggu lifestyle experience.",
            address: "Jl. Pantai Berawa No. 77",
            country: "Indonesia",
            latitude: -8.6476,
            longitude: 115.1385,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Rooftop Pool", "Gym", "Kitchen", "Balcony", "Rice Field View", "Smart TV", "Washer", "Scooter Parking", "Security", "Work Desk", "Coffee Maker", "Beach Nearby"],
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: "Boutique Hotel Suite in Sanur",
            city: "Bali",
            area: "Sanur",
            type: "Hotel",
            price: 1400000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
            isGuestFavorite: true,
            description: "Discover tranquil beachfront luxury at this boutique hotel suite in Sanur, Bali's most relaxed beach town. This 60-square-meter suite combines Balinese elegance with modern comfort. The spacious bedroom features a king-size bed with premium linens, traditional artwork, and direct access to a private garden terrace. The sitting area includes a comfortable daybed perfect for reading or afternoon naps. The marble bathroom showcases a deep soaking tub, rain shower, and luxury toiletries. Suite guests enjoy exclusive benefits including complimentary breakfast at the beachfront restaurant, sunset cocktails, and access to the hotel's spa and infinity pool overlooking the ocean. The hotel's Sanur location offers a peaceful alternative to busier Bali areas, with a beautiful beach promenade perfect for morning walks or cycling. Nearby attractions include traditional markets, authentic warungs, water sports centers, and the gateway to Nusa Penida and Nusa Lembongan islands. Ideal for couples seeking romance and relaxation.",
            address: "Jl. Danau Tamblingan No. 51",
            country: "Indonesia",
            latitude: -8.6982,
            longitude: 115.2612,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["WiFi", "Air Conditioning", "Beach Access", "Ocean View", "Infinity Pool", "Spa Access", "Restaurant", "Breakfast Included", "Room Service", "Private Terrace", "Bathtub", "Bicycle Rental", "Concierge", "Premium Toiletries"],
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: "Cliffside Villa in Uluwatu",
            city: "Bali",
            area: "Uluwatu",
            type: "Villa",
            price: 4200000,
            nights: 2,
            rating: 5.0,
            imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
            isGuestFavorite: true,
            description: "Perched dramatically on Uluwatu's limestone cliffs, this architectural masterpiece offers unparalleled views of the Indian Ocean and world-class sunsets. This 320-square-meter ultra-modern villa features floor-to-ceiling glass walls, minimalist design, and luxurious finishes throughout. The open-concept living area seamlessly connects to multiple terraces and a stunning infinity pool that appears to merge with the ocean horizon. Four spacious bedroom suites each offer breathtaking ocean views, designer furnishings, and spa-like en-suite bathrooms with outdoor showers. The gourmet kitchen is equipped with top-of-the-line appliances perfect for private chef services. Multiple lounging and dining areas take advantage of the spectacular setting. The villa includes a private cinema room, wine cellar, and gym. Full-time staff including butler, chef, and housekeepers ensure impeccable service. Located near Uluwatu's famous surf breaks, beach clubs like Sundays and Single Fin, and the iconic Uluwatu Temple, this villa represents the pinnacle of Bali luxury.",
            address: "Jl. Labuan Sait No. 9",
            country: "Indonesia",
            latitude: -8.8290,
            longitude: 115.0854,
            bedrooms: 4,
            bathrooms: 4,
            maxGuests: 8,
            petsAllowed: false,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1540541338287-41700207dee6",
                "https://images.unsplash.com/photo-1582719508461-905c673771fd",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
                "https://images.unsplash.com/photo-1505577058444-a3dab90d4253",
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "Infinity Pool", "Ocean View", "Cliff Location", "Full Kitchen", "Butler Service", "Personal Chef", "Cinema Room", "Gym", "Wine Cellar", "Multiple Terraces", "Outdoor Dining", "Sound System", "Premium Amenities"],
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: "Tropical House in Pererenan",
            city: "Bali",
            area: "Pererenan",
            type: "House",
            price: 1650000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
            isGuestFavorite: false,
            description: "Experience authentic Bali living in this charming tropical house located in the peaceful village of Pererenan. This 140-square-meter property perfectly balances traditional Balinese style with modern comforts. The open living area features high ceilings, natural ventilation, and doors that open to a private garden with a refreshing plunge pool. The house includes three comfortable bedrooms with air conditioning and ceiling fans, accommodating up to six guests. The master bedroom opens directly to the pool area, while the other bedrooms overlook lush tropical gardens. A fully equipped kitchen and outdoor dining area make it easy to enjoy home-cooked meals. The property is surrounded by rice fields, providing a serene atmosphere while remaining close to Canggu's surf beaches, yoga studios, and trendy cafes. This house is perfect for families, groups of friends, or anyone seeking an authentic Balinese experience away from tourist crowds while still having easy access to modern amenities.",
            address: "Jl. Pererenan No. 105",
            country: "Indonesia",
            latitude: -8.6389,
            longitude: 115.1237,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
                "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea",
                "https://images.unsplash.com/photo-1600607687644-c7171b42498f"
            ],
            amenities: ["WiFi", "Air Conditioning", "Plunge Pool", "Garden", "Rice Field View", "Full Kitchen", "Outdoor Dining", "Tropical Setting", "Parking", "Washer", "TV", "Work Desk", "BBQ Area", "Pet Friendly"],
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            name: "Beachside Condo in Jimbaran",
            city: "Bali",
            area: "Jimbaran",
            type: "Condo",
            price: 1550000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
            isGuestFavorite: true,
            description: "Wake up to ocean breezes in this elegant beachside condominium located in prestigious Jimbaran Bay. This 95-square-meter unit features a sophisticated coastal design with white-washed walls, natural wood accents, and large windows showcasing partial ocean views. The open living area flows onto a spacious balcony perfect for morning coffee or evening cocktails. The modern kitchen is fully equipped with quality appliances and granite countertops. Two well-appointed bedrooms offer comfortable queen-size beds and ample storage, with the master bedroom featuring an en-suite bathroom. Residents enjoy access to premium building amenities including a large swimming pool, fitness center, spa, and direct beach access. The condo is walking distance to Jimbaran's famous seafood restaurants where you can dine on the beach at sunset. The area offers a perfect balance of tranquility and convenience, with easy access to the airport, Uluwatu's attractions, and Nusa Dua's golf courses.",
            address: "Jl. Pantai Jimbaran No. 88",
            country: "Indonesia",
            latitude: -8.7692,
            longitude: 115.1653,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af"
            ],
            amenities: ["WiFi", "Air Conditioning", "Ocean View", "Beach Access", "Swimming Pool", "Gym", "Spa Access", "Kitchen", "Balcony", "Parking", "Security", "Smart TV", "Work Desk", "Coffee Maker"],
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },

        // Surabaya Properties (4)
        {
            name: "Executive Penthouse in Tunjungan Plaza Area",
            city: "Surabaya",
            area: "Tunjungan",
            type: "Penthouse",
            price: 2200000,
            nights: 2,
            rating: 4.8,
            imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
            isGuestFavorite: true,
            description: "Experience Surabaya's sophisticated urban lifestyle from this impressive penthouse located steps from the iconic Tunjungan Plaza. This 150-square-meter residence occupies the top floor with sweeping city views. The modern interior features an open-concept living area with designer furnishings, a gourmet kitchen with premium appliances, and floor-to-ceiling windows flooding the space with natural light. Two luxurious bedrooms include the master suite with a walk-in closet and spa-inspired bathroom with a deep soaking tub. The private rooftop terrace offers additional living space with lounge areas and panoramic city views. Building amenities include a swimming pool, fitness center, sauna, and 24-hour security. The location provides unmatched convenience with Tunjungan Plaza's luxury shopping, fine dining restaurants, and entertainment just steps away. Nearby attractions include House of Sampoerna museum and the historic Arab Quarter. Perfect for business executives and discerning travelers seeking premium accommodation in Surabaya's commercial heart.",
            address: "Jl. Basuki Rahmat No. 115",
            country: "Indonesia",
            latitude: -7.2656,
            longitude: 112.7395,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "15:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d"
            ],
            amenities: ["High-Speed WiFi", "Air Conditioning", "City View", "Rooftop Terrace", "Swimming Pool", "Gym", "Sauna", "Full Kitchen", "Smart TV", "Washer & Dryer", "Parking", "24/7 Security", "Elevator", "Work Desk", "Coffee Maker"],
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: "Business Hotel Suite in Darmo",
            city: "Surabaya",
            area: "Darmo",
            type: "Hotel",
            price: 780000,
            nights: 2,
            rating: 4.6,
            imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
            isGuestFavorite: false,
            description: "Stay productive and comfortable in this well-appointed business hotel suite located in Surabaya's upscale Darmo district. This 50-square-meter suite features a separate bedroom with a king-size bed and blackout curtains ensuring restful sleep, plus a living area with a comfortable sofa, work desk, and entertainment system. The modern bathroom includes both a bathtub and rain shower. Suite guests enjoy access to the executive lounge with complimentary breakfast, afternoon snacks, and evening cocktails. Hotel facilities include a rooftop pool with city views, a well-equipped gym, spa services, and an on-site restaurant serving Indonesian and international cuisine. The hotel's Darmo location places you near major shopping centers including Ciputra World and Galaxy Mall, numerous restaurants, and easy access to Surabaya's business districts. Whether visiting for business or leisure, this suite provides professional service and modern amenities for a comfortable Surabaya stay.",
            address: "Jl. Raya Darmo No. 99",
            country: "Indonesia",
            latitude: -7.2841,
            longitude: 112.7319,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["WiFi", "Air Conditioning", "Executive Lounge", "Rooftop Pool", "Gym", "Spa", "Restaurant", "Room Service", "Work Desk", "Smart TV", "Mini Bar", "Coffee Maker", "Bathtub", "Concierge"],
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            name: "Modern Apartment in Pakuwon City",
            city: "Surabaya",
            area: "Pakuwon City",
            type: "Apartment",
            price: 950000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
            isGuestFavorite: false,
            description: "Discover contemporary living in this sleek apartment located within Surabaya's premier Pakuwon City development. This 85-square-meter unit features modern design with clean lines, quality finishes, and practical amenities. The open living and dining area includes comfortable furnishings and large windows offering city views. The well-equipped kitchen features modern appliances and ample counter space. Two bedrooms provide comfortable sleeping arrangements with good storage, and the master bedroom includes an en-suite bathroom. Residents enjoy access to an extensive range of facilities including multiple swimming pools, tennis courts, basketball courts, jogging tracks, and a fitness center. The apartment's location within Pakuwon City means you're surrounded by shopping centers, supermarkets, restaurants, cafes, and entertainment venues. The integrated township concept provides everything you need within walking distance, while still offering easy access to other parts of Surabaya. Perfect for families or groups seeking modern comfort and comprehensive amenities.",
            address: "Jl. Mayjen Yono Suwoyo",
            country: "Indonesia",
            latitude: -7.2907,
            longitude: 112.6702,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Gym", "Tennis Court", "Basketball Court", "Kitchen", "TV", "Washer", "Parking", "Security", "Shopping Mall Access", "Work Desk", "Coffee Maker"],
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: "Colonial Style House in Gubeng",
            city: "Surabaya",
            area: "Gubeng",
            type: "House",
            price: 1450000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
            isGuestFavorite: true,
            description: "Step into Surabaya's rich history at this beautifully restored colonial-era house located in the established Gubeng neighborhood. This 170-square-meter property retains its original architectural charm with high ceilings, hardwood floors, large windows with wooden shutters, and a traditional front porch. The interior has been thoughtfully updated with modern amenities while preserving historical character. The spacious living and dining areas feature period-appropriate furniture mixed with contemporary comfort. Three comfortable bedrooms provide quality beds and air conditioning, with the master bedroom offering an en-suite bathroom. The fully equipped kitchen allows for home cooking, while the back garden provides outdoor space for relaxation. The house's central Gubeng location offers excellent access to business districts, universities, and Surabaya's attractions. Nearby you'll find the historic Gedung Grahadi, traditional markets, and authentic Surabayan restaurants. This house offers a unique opportunity to experience Surabaya's colonial heritage while enjoying modern comforts.",
            address: "Jl. Gubeng Kertajaya No. 77",
            country: "Indonesia",
            latitude: -7.2778,
            longitude: 112.7511,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: "15:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
                "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea",
                "https://images.unsplash.com/photo-1600607687644-c7171b42498f"
            ],
            amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Garden", "Colonial Architecture", "Hardwood Floors", "Parking", "TV", "Washer", "Dining Table", "Work Desk", "Coffee Maker", "Historical Property", "Pet Friendly"],
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },

        // Yogyakarta Properties (3)
        {
            name: "Heritage Villa in Kotagede",
            city: "Yogyakarta",
            area: "Kotagede",
            type: "Villa",
            price: 1800000,
            nights: 2,
            rating: 4.9,
            imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
            isGuestFavorite: true,
            description: "Experience Javanese royal heritage at this exquisite traditional villa located in historic Kotagede, the former capital of the Mataram Kingdom. This 200-square-meter property is a stunning example of traditional Javanese architecture with its joglo structure, carved wooden pillars, and intricate details throughout. The main pendopo serves as a grand living area with traditional seating and antique furnishings. Three beautifully appointed bedrooms feature traditional Javanese beds, batik textiles, and modern bathrooms with both traditional and contemporary fixtures. The villa includes a fully equipped kitchen and multiple courtyards with tropical gardens, reflecting pools, and traditional gazebos. Daily breakfast and housekeeping are included, with staff available to arrange cultural experiences including batik-making workshops, traditional dance performances, and visits to nearby silver craftsmen workshops. Located in the heart of Kotagede, you're surrounded by historical sites, traditional markets, and authentic Javanese culture. This villa offers an immersive experience for those seeking to understand Yogyakarta's rich cultural heritage.",
            address: "Jl. Mondorakan No. 45",
            country: "Indonesia",
            latitude: -7.8279,
            longitude: 110.4002,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
                "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"
            ],
            amenities: ["WiFi", "Air Conditioning", "Traditional Architecture", "Tropical Garden", "Reflecting Pool", "Full Kitchen", "Cultural Experiences", "Housekeeping", "Breakfast Included", "Antique Furnishings", "Multiple Courtyards", "Batik Textiles", "Cultural Tours", "Historical Location"],
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            name: "Boutique Hotel in Prawirotaman",
            city: "Yogyakarta",
            area: "Prawirotaman",
            type: "Hotel",
            price: 650000,
            nights: 2,
            rating: 4.7,
            imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
            isGuestFavorite: false,
            description: "Discover Yogyakarta's charm from this intimate boutique hotel located on the famous Prawirotaman Street. This 40-square-meter deluxe room combines traditional Javanese aesthetics with modern comfort. The room features a comfortable king-size bed with quality linens, traditional batik artwork, carved wooden furniture, and a modern bathroom with hot water shower. French doors open to a small private terrace overlooking the hotel's lush courtyard garden. Guests enjoy complimentary breakfast served in the traditional Javanese-style restaurant, use of bicycles for exploring the neighborhood, and the hotel's swimming pool surrounded by tropical plants. The friendly staff can arrange tours to Borobudur Temple, Prambanan Temple, and other attractions. Prawirotaman Street offers an eclectic mix of restaurants, cafes, bars, art galleries, and handicraft shops, all within walking distance. The hotel provides a perfect base for cultural exploration while offering a peaceful retreat at the end of the day.",
            address: "Jl. Prawirotaman No. 28",
            country: "Indonesia",
            latitude: -7.8132,
            longitude: 110.3764,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "12:00",
            images: [
                "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
                "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                "https://images.unsplash.com/photo-1590490360182-c33d57733427"
            ],
            amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Restaurant", "Breakfast Included", "Bicycle Rental", "Garden View", "Private Terrace", "Hot Water", "Tour Arrangements", "Traditional Decor", "Coffee Maker"],
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            name: "Contemporary Apartment in Sleman",
            city: "Yogyakarta",
            area: "Sleman",
            type: "Apartment",
            price: 580000,
            nights: 2,
            rating: 4.5,
            imageUrl: "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
            isGuestFavorite: false,
            description: "Experience modern comfort in this well-appointed apartment located in Yogyakarta's developing Sleman area. This 70-square-meter unit features a contemporary design with an open living and dining area, modern furnishings, and good natural lighting. The compact kitchen is equipped with essential appliances and a small breakfast bar. Two comfortable bedrooms provide quality beds and adequate storage, perfect for small families or groups. The apartment building offers basic amenities including elevator access, parking, and 24-hour security. Located near Gadjah Mada University, the area offers numerous student-friendly cafes, restaurants, and affordable eateries serving authentic Javanese cuisine. The apartment provides easy access to major attractions including the Sultan's Palace (Kraton), Malioboro Street, and Prambanan Temple, while being far enough from tourist areas to offer a more local experience. This apartment is ideal for budget-conscious travelers, students, or anyone seeking comfortable accommodation at a reasonable price.",
            address: "Jl. Affandi No. 198",
            country: "Indonesia",
            latitude: -7.7767,
            longitude: 110.3773,
            bedrooms: 2,
            bathrooms: 1,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: "14:00",
            checkOutTime: "11:00",
            images: [
                "https://images.unsplash.com/photo-1502672260066-6bc35f0b1525",
                "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                "https://images.unsplash.com/photo-1540518614846-7eded433c457"
            ],
            amenities: ["WiFi", "Air Conditioning", "Kitchen", "TV", "Elevator", "Parking", "Security", "Work Desk", "Coffee Maker", "Hot Water", "Nearby Restaurants", "University Area"],
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
    ];

    await db.insert(properties).values(sampleProperties);
    
    console.log('✅ Properties seeder completed successfully - 30 properties created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});