import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        // Jakarta Properties (8 total)
        {
            name: 'Luxurious Menteng Apartment',
            city: 'Jakarta',
            area: 'Menteng',
            type: 'Apartment',
            price: 850000,
            nights: 2,
            rating: 4.98,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Modern Menteng Condo',
            city: 'Jakarta',
            area: 'Kecamatan Menteng',
            type: 'Condo',
            price: 780000,
            nights: 2,
            rating: 4.95,
            imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cozy Grogol Apartment',
            city: 'Jakarta',
            area: 'Grogol petamburan',
            type: 'Apartment',
            price: 420000,
            nights: 2,
            rating: 4.87,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Elegant Cilandak Residence',
            city: 'Jakarta',
            area: 'Kecamatan Cilandak',
            type: 'Guesthouse',
            price: 550000,
            nights: 2,
            rating: 4.90,
            imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Premium Kebayoran Condo',
            city: 'Jakarta',
            area: 'Kebayoran Baru',
            type: 'Condo',
            price: 901550,
            nights: 2,
            rating: 5.0,
            imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cozy Kebayoran Guesthouse',
            city: 'Jakarta',
            area: 'Kebayoran Baru',
            type: 'Guesthouse',
            price: 320000,
            nights: 2,
            rating: 4.83,
            imageUrl: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Premium Bekasi Living',
            city: 'Jakarta',
            area: 'Kecamatan Bekasi',
            type: 'Apartment',
            price: 680000,
            nights: 2,
            rating: 4.93,
            imageUrl: 'https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Stylish Bekasi Condo',
            city: 'Jakarta',
            area: 'Kecamatan Bekasi',
            type: 'Condo',
            price: 195418,
            nights: 2,
            rating: 4.85,
            imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Kabupaten Tangerang Properties (8 total)
        {
            name: 'BSD Modern Apartment',
            city: 'Kabupaten Tangerang',
            area: 'BSD City',
            type: 'Apartment',
            price: 720000,
            nights: 2,
            rating: 4.96,
            imageUrl: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Serpong Luxury Condo',
            city: 'Kabupaten Tangerang',
            area: 'Serpong',
            type: 'Condo',
            price: 875000,
            nights: 2,
            rating: 4.98,
            imageUrl: 'https://images.unsplash.com/photo-1501183638710-841dd1904471?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Gading Villa Retreat',
            city: 'Kabupaten Tangerang',
            area: 'Gading Serpong',
            type: 'Villa',
            price: 890000,
            nights: 2,
            rating: 5.0,
            imageUrl: 'https://images.unsplash.com/photo-1571508601891-ca5e7a713859?w=800',
            isGuestFavorite: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Karawaci Cozy Stay',
            city: 'Kabupaten Tangerang',
            area: 'Karawaci',
            type: 'Guesthouse',
            price: 380000,
            nights: 2,
            rating: 4.87,
            imageUrl: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Alam Sutera Executive Apartment',
            city: 'Kabupaten Tangerang',
            area: 'Alam Sutera',
            type: 'Apartment',
            price: 650000,
            nights: 2,
            rating: 4.93,
            imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Bintaro Premium Living',
            city: 'Kabupaten Tangerang',
            area: 'Bintaro',
            type: 'Condo',
            price: 790000,
            nights: 2,
            rating: 4.95,
            imageUrl: 'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cisauk Garden Villa',
            city: 'Kabupaten Tangerang',
            area: 'Cisauk',
            type: 'Villa',
            price: 520000,
            nights: 2,
            rating: 4.90,
            imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pamulang Comfort Apartment',
            city: 'Kabupaten Tangerang',
            area: 'Pamulang',
            type: 'Apartment',
            price: 440000,
            nights: 2,
            rating: 4.85,
            imageUrl: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800',
            isGuestFavorite: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(properties).values(sampleProperties);
    
    console.log('✅ Properties seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});