import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // Property 93: Beachfront Villa in Seminyak (12 reviews) - Luxury
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Emma Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 5.0,
            comment: 'Absolutely stunning beachfront villa in the heart of Seminyak! The location is unbeatable - literally steps from the beach where we watched incredible sunsets every evening. The villa itself is luxurious with a beautiful infinity pool overlooking the ocean. We loved being close to all the trendy beach clubs and restaurants. The staff arranged a private dinner on the beach which was magical. Highly recommend for anyone wanting luxury beach living in Bali!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'James Mitchell',
            userAvatar: null,
            rating: 4.9,
            comment: 'What a phenomenal stay at this Seminyak beachfront property! My wife and I celebrated our anniversary here and it exceeded all expectations. The villa design is contemporary yet embraces Balinese aesthetics beautifully. Morning coffees by the pool watching surfers and evening walks on the beach were highlights. Seminyak nightlife is fantastic - so many great bars and restaurants within walking distance. The villa staff were attentive without being intrusive. Worth every rupiah for this level of luxury and location.',
            cleanliness: 4.9,
            accuracy: 5.0,
            communication: 4.9,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-07-22').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Sophie Chen',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 4.8,
            comment: 'Magnificent beachfront villa that captures everything special about Seminyak. We spent most mornings doing yoga on the deck overlooking the ocean and afternoons exploring the vibrant beach club scene. The villa is spacious, modern, and perfectly maintained. Being able to walk to iconic spots like Ku De Ta and Potato Head was convenient. The only minor downside is the lively atmosphere means some street noise, but that is part of Seminyak charm. Perfect for those who want beach luxury with buzzing nightlife nearby.',
            cleanliness: 4.8,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Lucas Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 5.0,
            comment: 'This villa is absolute paradise! As an Australian who visits Bali regularly, I can confidently say this is one of the finest beachfront properties in Seminyak. The attention to detail is remarkable - from the outdoor shower surrounded by tropical plants to the sunken living room with panoramic ocean views. We hosted a small gathering and the staff helped arrange everything perfectly. The beach here is great for sunset strolls and the surf is decent too. Cannot fault anything about this property.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-06-18').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Isabella Rodriguez',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 4.7,
            comment: 'Breathtaking villa right on Seminyak beach! Waking up to ocean sounds and having breakfast with sand between your toes is unforgettable. The villa combines modern luxury with traditional Balinese touches which we loved. Pool area is stunning for lounging during the day. Being in central Seminyak means easy access to shopping, dining, and nightlife. Staff were helpful with recommendations and booking restaurants. Only small issue was occasional power fluctuations but typical for Bali. Overall an incredible beachfront experience.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 5.0,
            value: 4.5,
            createdAt: new Date('2024-08-30').toISOString(),
            updatedAt: new Date('2024-08-30').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Oliver Williams',
            userAvatar: null,
            rating: 4.9,
            comment: 'Fantastic luxury villa in prime Seminyak location! The direct beach access is the star feature - we were on the sand in seconds for morning runs and sunset watching. Interior is spacious with high-end furnishings and the outdoor areas are designed for tropical living. Pool is large enough for proper swimming. Loved the proximity to Seminyak trendy restaurant scene - tried a different spot each night. Villa comes with excellent security and privacy despite being in a busy area. Highly recommended for beach lovers.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-07-10').toISOString(),
            updatedAt: new Date('2024-07-10').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Aiko Tanaka',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 5.0,
            comment: 'Perfect beachfront retreat in Seminyak! This villa exceeded our expectations in every way. The architecture is stunning with floor-to-ceiling windows that bring the ocean views inside. We particularly enjoyed the outdoor dining pavilion where we had fresh seafood delivered. The beach is beautiful for swimming and the sunsets are spectacular. Staff arranged surfing lessons which was fun. Location means you can walk to great restaurants and shops but villa feels private and peaceful. Truly a five-star property.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Michael OBrien',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.8,
            comment: 'Brilliant beachfront villa for our family holiday from Sydney! Kids loved having direct beach access and the pool was perfect. Villa is spacious with multiple living areas which gave everyone their space. Seminyak beach here is relatively calm and great for kids. We walked to nearby warungs for authentic Indonesian food and explored the boutique shops. Air conditioning worked perfectly throughout. Staff were accommodating with our requests. Great base for exploring southern Bali while enjoying luxury beachfront living.',
            cleanliness: 4.8,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-06-28').toISOString(),
            updatedAt: new Date('2024-06-28').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Clara Dubois',
            userAvatar: null,
            rating: 4.9,
            comment: 'Spectacular villa with unparalleled beach access! Coming from Paris, we wanted authentic Bali beach experience and found it here. The open-plan design lets ocean breezes flow through naturally. Mornings with coffee watching surfers and evenings with cocktails watching sunsets became our routine. Villa is beautifully decorated with local art and comfortable furniture. Seminyak vibrant energy is exciting - loved the beach clubs and restaurant scene. Staff helped arrange everything from spa treatments to driver services. Memorable beachfront stay!',
            cleanliness: 4.9,
            accuracy: 5.0,
            communication: 4.9,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-08-02').toISOString(),
            updatedAt: new Date('2024-08-02').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Ryan McKenzie',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.7,
            comment: 'Top-notch beachfront property in Seminyak! As frequent Bali visitors, we appreciate quality and this villa delivers. Direct beach access is wonderful for morning swims and the infinity pool seamlessly blends with ocean horizon. Interior is luxuriously appointed with modern amenities while maintaining Balinese character. Being in central Seminyak means walking distance to everything but villa gates ensure privacy. Enjoyed exploring local markets and trying different cafes daily. Minor traffic noise occasionally but expected in popular area. Overall excellent luxury beach experience.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Natasha Kumar',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 5.0,
            comment: 'Dream beachfront villa in Seminyak! My husband and I needed a relaxing getaway and this was perfect. Villa design maximizes ocean views from every room. We loved the outdoor bathroom with tropical garden - so luxurious! Spent days lounging by pool and evenings exploring Seminyak restaurant scene. Beach is beautiful for sunset walks. Staff were fantastic - helped book reservations and arranged private car when needed. Villa has everything for comfortable stay. Worth the splurge for this level of beachfront luxury and prime location.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-09-12').toISOString(),
        },
        {
            propertyId: 93,
            carId: null,
            userId: null,
            userName: 'Benjamin Park',
            userAvatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150',
            rating: 4.8,
            comment: 'Outstanding beachfront villa experience! Location is superb - right on Seminyak beach with easy access to everything the area offers. Villa itself is stunning with contemporary design and high-quality finishes throughout. Pool and deck area are beautifully landscaped with tropical plants creating private oasis feel. We particularly enjoyed the media room for relaxing evenings. Being able to walk to popular beach clubs and restaurants was convenient. Staff communication excellent and maintenance was prompt. Fantastic property for luxury beach holiday in Bali.',
            cleanliness: 4.8,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-06-05').toISOString(),
            updatedAt: new Date('2024-06-05').toISOString(),
        },

        // Property 94: Luxury Penthouse in Nusa Dua (10 reviews) - Luxury
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Victoria Hamilton',
            userAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150',
            rating: 5.0,
            comment: 'Incredible luxury penthouse in prestigious Nusa Dua! The panoramic ocean views from the rooftop terrace are simply breathtaking. We spent evenings watching sunset over the Indian Ocean with champagne. Penthouse is impeccably designed with modern furnishings and every amenity imaginable. Nusa Dua is perfect for those seeking refined elegance - pristine beaches, world-class resorts, and excellent golf courses nearby. Building security is excellent and staff were professional. Private plunge pool on terrace was highlight. Perfect for couples seeking upscale Bali experience.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Alexander Schmidt',
            userAvatar: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=150',
            rating: 4.9,
            comment: 'Absolutely stunning penthouse in Nusa Dua resort enclave! Coming from Germany, we appreciated the quality and attention to detail. Floor-to-ceiling windows throughout provide incredible light and ocean views. Master suite is enormous with luxurious bathroom. Rooftop entertaining area is perfect for dinners under stars. Nusa Dua beaches are immaculate - we walked to beach clubs daily. Loved peaceful atmosphere compared to Seminyak bustle. Complex has excellent facilities including gym and spa. Minor issue with AC remote but quickly resolved. Outstanding luxury accommodation.',
            cleanliness: 4.9,
            accuracy: 5.0,
            communication: 4.9,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-08').toISOString(),
            updatedAt: new Date('2024-07-08').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Priya Sharma',
            userAvatar: null,
            rating: 4.8,
            comment: 'Magnificent penthouse with spectacular views! This property truly offers five-star living in Nusa Dua. We loved the spacious layout with three bedrooms perfect for our family. Kitchen is fully equipped with high-end appliances. Rooftop terrace became our favorite spot - incredible for morning yoga and evening relaxation. Nusa Dua is beautifully maintained with manicured beaches and upscale shopping. Easy access to water sports and cultural attractions. Building concierge helped arrange everything. Only wish we had stayed longer to fully enjoy all amenities.',
            cleanliness: 4.8,
            accuracy: 4.9,
            communication: 4.8,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Marcus Johnson',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
            rating: 5.0,
            comment: 'Phenomenal luxury penthouse! We celebrated our 25th anniversary here and it was perfect. The panoramic views are stunning - you can see the ocean, resort grounds, and distant temple silhouettes. Interior design is sophisticated with contemporary Balinese touches. Smart home technology controls everything from lighting to curtains. Nusa Dua pristine beaches are just minutes away. We enjoyed fine dining at nearby five-star resort restaurants and spa days. Rooftop infinity pool is perfect size for cooling off. Truly exceeded expectations for luxury Bali accommodation.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-06-20').toISOString(),
            updatedAt: new Date('2024-06-20').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Sarah Davidson',
            userAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
            rating: 4.7,
            comment: 'Beautiful penthouse in exclusive Nusa Dua location! Coming from Melbourne, we wanted upscale relaxation and found it here. Rooftop space is incredible with lounge areas, dining table, and plunge pool. Interior is elegantly furnished with comfortable living spaces. Master bedroom opens to ocean views which we woke to daily. Nusa Dua is wonderfully peaceful with excellent restaurants within walking distance. Enjoyed water sports at beach and golf at nearby championship course. Staff responsive to inquiries. Slight echo in living area but minor issue. Highly recommend for luxury seekers.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Hiroshi Watanabe',
            userAvatar: 'https://images.unsplash.com/photo-1495603889488-42d1d66e5523?w=150',
            rating: 4.9,
            comment: 'Exceptional luxury penthouse in Nusa Dua! The quality of finishes and attention to detail is impressive. Spacious open-plan living leads to expansive terrace with unobstructed ocean panorama. Kitchen has everything needed for entertaining. We hosted dinner on rooftop and guests were amazed by setting. Nusa Dua offers sophisticated atmosphere - pristine environment with world-class amenities nearby. Complex grounds are immaculate with beautiful landscaping. Staff professional and helpful. Only minor note is limited parking for guests but managed well. Perfect penthouse for discerning travelers.',
            cleanliness: 4.9,
            accuracy: 5.0,
            communication: 4.9,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-07-25').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Emily Foster',
            userAvatar: null,
            rating: 4.8,
            comment: 'Gorgeous penthouse with amazing amenities! This property combines luxury with practicality perfectly. Rooftop terrace is the showstopper - we spent most time there enjoying views and private pool. Interior is modern and stylish with high-quality everything. Bedrooms are spacious with excellent beds for restful sleep. Nusa Dua location is ideal for peaceful holiday - beautiful beaches without crowds, excellent dining options, and easy airport access. Building has great security and underground parking. Staff responsive via WhatsApp. Absolutely loved our stay and would return!',
            cleanliness: 4.8,
            accuracy: 4.9,
            communication: 4.8,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-09-01').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Daniel Cooper',
            userAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150',
            rating: 5.0,
            comment: 'Outstanding luxury penthouse experience! The rooftop terrace alone is worth booking this property - sunrise yoga and sunset cocktails with ocean views became our daily ritual. Interior is impeccably maintained with designer furniture and art. Smart home features make everything convenient. Nusa Dua is perfect for those seeking upscale tranquility - we explored beautiful beaches, played golf, and enjoyed spa treatments at nearby resorts. Staff arranged private chef one evening which was fantastic. Cannot recommend highly enough for luxury Bali getaway.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-06-12').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Olivia Bennett',
            userAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150',
            rating: 4.7,
            comment: 'Fabulous penthouse in prime Nusa Dua! The views are absolutely incredible from every angle. We particularly loved the wrap-around terrace perfect for morning coffee and evening dining. Interior design is contemporary and sophisticated with neutral tones and pops of Balinese color. Bathrooms are spa-like with rainfall showers. Nusa Dua pristine beaches and upscale resorts make it feel like exclusive retreat. Enjoyed water sports and exploring local temples. Complex facilities including gym and pool were excellent. Minor wifi issues occasionally but staff addressed quickly. Wonderful luxury accommodation.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            propertyId: 94,
            carId: null,
            userId: null,
            userName: 'Thomas Reynolds',
            userAvatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=150',
            rating: 4.9,
            comment: 'Spectacular penthouse that defines luxury living! Coming from London, we were impressed by quality and space. Rooftop is entertainment paradise - kitchen, dining, lounging, and pool all with panoramic ocean backdrop. Interior has everything from wine fridge to sound system throughout. Bedrooms offer privacy and comfort. Nusa Dua is gem for those seeking refined Bali experience - immaculate beaches, championship golf, and fine dining. Staff were professional and helpful with recommendations. Building amenities excellent. Only note is AC noise at night but adjustable. Highly recommended premium property.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },

        // Property 95: Traditional Villa in Ubud (11 reviews) - Luxury
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Charlotte Martin',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
            rating: 5.0,
            comment: 'Absolutely magical traditional villa in the heart of Ubud! Waking up to rice terrace views and jungle sounds was incredibly peaceful. The villa beautifully showcases authentic Balinese architecture with carved wooden doors and traditional thatched roofs. We loved exploring Ubud cultural scene - temples, art galleries, and traditional dance performances. The villa staff arranged a cooking class which was highlight. Pool overlooking rice paddies was perfect for afternoon relaxation. Walking distance to Ubud center with amazing restaurants and markets. This is the real Bali experience everyone dreams of!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-08').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'David Lee',
            userAvatar: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=150',
            rating: 4.9,
            comment: 'Stunning traditional villa with breathtaking rice terrace vistas! This property captures essence of Ubud perfectly. Traditional architecture combined with modern comforts makes it ideal base for cultural exploration. We visited Tegalalang rice terraces, sacred Monkey Forest, and numerous art workshops. Villa has beautiful outdoor spaces - the garden pavilion became our favorite meditation spot. Staff were wonderful, arranging drivers and recommending authentic warungs. Mornings with coffee overlooking terraces were serene. Only minor issue was occasional insect visitors but expected in jungle setting. Absolutely loved the authentic Ubud experience.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-18').toISOString(),
            updatedAt: new Date('2024-07-18').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Maria Santos',
            userAvatar: null,
            rating: 4.8,
            comment: 'Beautiful traditional villa in peaceful Ubud location! The property feels like stepping into authentic Bali with its traditional design and natural surroundings. Rice terrace views are spectacular especially during sunrise. We enjoyed yoga sessions in the garden pavilion and exploring nearby Campuhan Ridge Walk. Ubud artistic energy is inspiring - so many galleries and craft workshops. Villa is comfortable with good amenities while maintaining traditional charm. Staff helped arrange visits to temples and traditional ceremonies. Loved the organic produce from local markets. Perfect for those seeking cultural immersion and tranquility.',
            cleanliness: 4.8,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-08-22').toISOString(),
            updatedAt: new Date('2024-08-22').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Andrew Walsh',
            userAvatar: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=150',
            rating: 5.0,
            comment: 'Incredible traditional Balinese villa experience! Coming from Perth, we wanted authentic cultural immersion and this villa delivered perfectly. Traditional architecture is stunning with intricate carvings and open-air living spaces. Waking to gamelan music from nearby temple and rice terrace views was magical. Ubud offers endless exploration - temples, waterfalls, art museums. Villa staff were exceptional, arranging everything from spa treatments to temple visits. Pool area surrounded by tropical gardens feels like private oasis. Perfect blend of tradition and comfort. Highly recommend for authentic Ubud experience.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-06-25').toISOString(),
            updatedAt: new Date('2024-06-25').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Sophie Laurent',
            userAvatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150',
            rating: 4.7,
            comment: 'Charming traditional villa nestled in Ubud rice fields! The setting is absolutely enchanting with emerald terraces stretching as far as you can see. Villa design honors Balinese traditions with thatched roofs and carved stone details. We spent days exploring Ubud spiritual side - yoga studios, meditation centers, and healing practices. Loved the organic cafes and vibrant art scene. Villa has peaceful energy perfect for relaxation and reflection. Staff arranged silver-making workshop which was fascinating. Only note is villa requires navigation of stairs but part of traditional design. Wonderful cultural experience.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Ryan Murphy',
            userAvatar: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=150',
            rating: 4.9,
            comment: 'Phenomenal traditional villa with spectacular rice terrace panoramas! This property is perfect for experiencing real Balinese culture. Architecture is authentically traditional yet equipped with modern amenities for comfortable stay. Mornings practicing yoga on the pavilion overlooking terraces were highlights. Ubud vibrant culture kept us busy - temple ceremonies, traditional markets, art galleries. Villa location is peaceful yet close enough to walk to restaurants. Staff went above and beyond arranging cooking class and waterfall tours. Pool and gardens are beautifully maintained. Absolutely loved the authentic Ubud experience this villa provides.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-05').toISOString(),
            updatedAt: new Date('2024-07-05').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Jessica Wong',
            userAvatar: null,
            rating: 4.8,
            comment: 'Gorgeous traditional villa surrounded by nature! The rice terrace views are simply stunning and change beautifully throughout day. Villa architecture is authentically Balinese with open-air concept that brings nature inside. We loved exploring Ubud - visited Sacred Monkey Forest, numerous temples, and took traditional painting class. Villa has wonderful energy, perfect for digital detox and reconnection with nature. Staff were helpful and knowledgeable about area. Enjoyed delicious breakfasts on terrace watching farmers tend rice paddies. Minor issue with hot water consistency but manageable. Overall wonderful traditional Ubud experience.',
            cleanliness: 4.8,
            accuracy: 4.8,
            communication: 4.8,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Matthew Richardson',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
            rating: 5.0,
            comment: 'Outstanding traditional villa in magical Ubud setting! The property perfectly balances authentic Balinese design with modern comfort. Rice terrace views are breathtaking especially during golden hour. We immersed ourselves in Ubud culture - attended temple ceremonies, explored art markets, tried traditional healing. Villa staff were exceptional, sharing local knowledge and arranging meaningful experiences. Loved morning walks through nearby villages and yoga sessions in garden. Pool area is serene with jungle backdrop. This villa offers genuine cultural experience while providing luxury comfort. Highly recommend for authentic Bali.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-06-08').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Hannah Collins',
            userAvatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150',
            rating: 4.7,
            comment: 'Lovely traditional villa in heart of Ubud! Waking up to rice terrace sunrise and bird songs was incredibly peaceful. Villa showcases beautiful Balinese craftsmanship with carved wood and stone throughout. We explored Ubud cultural offerings - traditional dance performances, art workshops, and spiritual ceremonies. Location is tranquil yet convenient to restaurants and shops. Villa gardens are lush with tropical plants and flowers. Staff arranged bike tour through rice paddies which was memorable. Only note is some insects due to natural setting but part of experience. Wonderful place for cultural exploration and relaxation.',
            cleanliness: 4.7,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Nicholas Taylor',
            userAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
            rating: 4.9,
            comment: 'Fantastic traditional villa with amazing rice terrace outlook! The villa captures essence of Ubud beautifully with traditional architecture and natural surroundings. We spent our days exploring temples, learning about Balinese Hinduism, and enjoying yoga classes. Villa has peaceful ambiance perfect for meditation and reflection. Staff were knowledgeable about local culture and arranged temple visits and traditional ceremonies. Loved the outdoor shower surrounded by tropical plants. Pool overlooking terraces is stunning spot for sunset. Great base for experiencing authentic Balinese culture and Ubud artistic scene. Highly recommended.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 4.9,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-07-28').toISOString(),
            updatedAt: new Date('2024-07-28').toISOString(),
        },
        {
            propertyId: 95,
            carId: null,
            userId: null,
            userName: 'Amelia Brown',
            userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
            rating: 4.8,
            comment: 'Beautiful traditional villa offering authentic Ubud experience! The rice terrace views are postcard-perfect and constantly changing with light. Villa design is traditional Balinese with modern updates making it comfortable for extended stay. We explored everything Ubud offers - temples, waterfalls, art markets, cooking classes. Location is peaceful yet close to action. Villa staff were helpful arranging transportation and activities. Enjoyed morning coffees on terrace watching sunrise over paddies. Gardens are beautifully landscaped with tropical flowers. Perfect property for those seeking cultural immersion and natural beauty. Would definitely return!',
            cleanliness: 4.8,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-08-18').toISOString(),
        },

        // Property 96: Modern Apartment in Canggu (8 reviews) - Mid-range
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Jake Morrison',
            userAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150',
            rating: 4.6,
            comment: 'Great modern apartment in the heart of Canggu! Perfect location for surf and digital nomad lifestyle. Walking distance to awesome cafes, coworking spaces, and beaches. The apartment is clean and functional with good wifi for remote work. Loved the rooftop pool with sunset views. Canggu vibe is relaxed yet buzzing - so many international restaurants and beach clubs. We surfed daily at nearby breaks and explored the cafe scene. Only minor issue was occasional noise from neighboring bars but expected in lively Canggu. Great value for money in prime location.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Lisa Chen',
            userAvatar: null,
            rating: 4.5,
            comment: 'Nice apartment in trendy Canggu area! The location is excellent for experiencing Canggu lifestyle - hipster cafes, yoga studios, and surf beaches all nearby. Apartment is modern with comfortable furnishings and kitchen has everything needed. We enjoyed exploring local warungs and international restaurants. Canggu has great energy with mix of locals, expats, and travelers. Building pool area is nice for relaxing after beach days. Staff were responsive via messaging. Only note is parking can be tight and traffic heavy during peak times. Overall good value accommodation in happening Canggu.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Tom Wilson',
            userAvatar: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150',
            rating: 4.7,
            comment: 'Solid modern apartment in prime Canggu spot! Coming from Sydney to surf, this location was perfect. Short bike ride to Echo Beach and Batu Bolong. Apartment has good amenities including decent wifi for work. Loved the cafe culture here - tried different brunch spots daily. Canggu has transformed into digital nomad hub with great coworking spaces. Building is secure with friendly staff. Pool and gym facilities are nice additions. Only issue was hot water occasionally temperamental. Overall great base for experiencing Canggu surf and cafe lifestyle. Would stay again.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-07-12').toISOString(),
            updatedAt: new Date('2024-07-12').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Emma Roberts',
            userAvatar: 'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=150',
            rating: 4.4,
            comment: 'Good apartment for Canggu exploration! The modern design is clean and practical. We spent most time exploring Canggu - from traditional temples to trendy beach clubs. Location puts you in center of action with restaurants and shops nearby. Apartment building has nice pool though can get busy. Kitchen is adequately equipped for simple meals. Enjoyed walking to Pererenan Beach and checking out Canggu Shortcut market. Staff communication could be more responsive but generally helpful. Minor issue with AC noise but manageable. Decent value for staying in popular Canggu area.',
            cleanliness: 4.4,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-09-22').toISOString(),
            updatedAt: new Date('2024-09-22').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Mark Peterson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.6,
            comment: 'Comfortable modern apartment in vibrant Canggu! Great location for digital nomads - fast wifi, comfortable workspace, and surrounded by cafes. We balanced work with surfing and exploring. Canggu has amazing food scene from healthy bowls to international cuisine. Apartment is well-maintained with modern fixtures. Building facilities including pool and security are good. Enjoyed being able to walk or bike most places. Traffic can be chaotic but part of Canggu experience. Only minor maintenance issue was quickly resolved. Good value for long-term stay in Canggu.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-06-18').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Sarah Kim',
            userAvatar: null,
            rating: 4.5,
            comment: 'Nice apartment in happening Canggu location! Perfect for experiencing the unique Canggu vibe. We loved exploring endless cafe options and yoga studios. Apartment is modern and functional with good natural light. Kitchen is useful for preparing healthy meals with ingredients from local markets. Building pool is pleasant for afternoon dips. Location means walking distance to beaches and nightlife. Staff were friendly though response time varied. Minor issue with cleanliness upon arrival but addressed. Overall good option for Canggu stay especially for younger travelers and digital nomads.',
            cleanliness: 4.4,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-28').toISOString(),
            updatedAt: new Date('2024-08-28').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Alex Turner',
            userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
            rating: 4.7,
            comment: 'Great modern apartment for Canggu lifestyle! The location is fantastic - close to popular surf breaks and best cafes. Apartment has contemporary design with comfortable living space. We worked remotely with no wifi issues and spent afternoons surfing or exploring. Canggu energy is perfect mix of laid-back and lively. Loved the variety of international restaurants and beach clubs. Building has good security and amenities. Only note is can hear traffic noise but expected in central location. Excellent value for staying in most happening area of Bali. Highly recommend for Canggu experience.',
            cleanliness: 4.7,
            accuracy: 4.7,
            communication: 4.6,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        {
            propertyId: 96,
            carId: null,
            userId: null,
            userName: 'Rachel Green',
            userAvatar: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=150',
            rating: 4.5,
            comment: 'Solid apartment in prime Canggu spot! Perfect base for exploring this unique area. We enjoyed the proximity to beaches and cafe scene. Apartment is clean and modern with good amenities. Canggu has incredible food variety - from local warungs to upscale restaurants. We tried yoga classes, surfing lessons, and just soaking up the creative vibe. Building pool and gym were nice extras. Staff communication was generally good. Minor issue with occasional water pressure but not major. Good value for staying in Canggu especially compared to hotel prices. Would recommend for casual Bali experience.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },

        // Property 97: Boutique Hotel Suite in Sanur (9 reviews) - Mid-range
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Patricia Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=150',
            rating: 4.6,
            comment: 'Lovely boutique hotel suite in peaceful Sanur! Perfect for relaxing beach holiday away from crowds. Sanur has beautiful long beach perfect for morning walks and stunning sunrises. Suite is charming with comfortable furnishings and nice balcony. Hotel staff were friendly and helpful with recommendations. We enjoyed exploring Sanur beachfront promenade with its cafes and restaurants. The area has more traditional Bali feel compared to Seminyak or Canggu. Loved the calm water perfect for swimming and stand-up paddleboarding. Good value for peaceful beach stay with excellent location and service.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Robert Hughes',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
            rating: 4.5,
            comment: 'Nice boutique suite in tranquil Sanur! Coming from Brisbane, we wanted peaceful escape and Sanur delivered. Beach is beautiful with calm water ideal for families. Suite has good amenities and comfortable bed. Hotel has charming character with tropical gardens. We enjoyed bike rides along beachfront path and exploring local art markets. Sanur has relaxed atmosphere with good restaurants serving fresh seafood. Staff were attentive and arranged day trips. Only minor issue was limited parking but managed. Great value for quiet beach holiday with traditional Balinese hospitality.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-07-08').toISOString(),
            updatedAt: new Date('2024-07-08').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Jennifer Moore',
            userAvatar: null,
            rating: 4.7,
            comment: 'Charming boutique hotel suite in lovely Sanur! The peaceful atmosphere was exactly what we needed. Suite is well-appointed with comfortable living space and good bathroom. Hotel grounds are beautiful with lush gardens. Sanur beach is wonderful - safe swimming and beautiful sunrise views. We loved the laid-back vibe compared to busier areas. Beachfront has great restaurants and cafes. Staff were helpful arranging snorkeling trips and cultural tours. Hotel breakfast was delicious. Only note is suite could use minor updates but overall very comfortable. Excellent choice for relaxing Sanur stay.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-09-12').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Michael Stevens',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.4,
            comment: 'Good boutique suite in quiet Sanur location! Perfect for those seeking peaceful beach holiday. Suite is comfortable with nice balcony for morning coffee. Hotel has traditional Balinese charm with friendly staff. Sanur beach is family-friendly with calm water and beautiful scenery. We enjoyed leisurely beach walks and trying local warungs. Area has more authentic feel compared to tourist hotspots. Staff helped arrange taxi to explore other parts of Bali. Minor issue with wifi reliability but not major concern. Decent value for Sanur stay with good service and location.',
            cleanliness: 4.4,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-06-22').toISOString(),
            updatedAt: new Date('2024-06-22').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Susan Walker',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.6,
            comment: 'Pleasant boutique hotel suite in serene Sanur! We appreciated the tranquil environment after busy city life. Suite is well-maintained with comfortable amenities. Hotel has lovely pool area with tropical landscaping. Sanur is perfect for relaxation - beautiful beach for swimming and peaceful atmosphere. We enjoyed exploring local markets and trying traditional Balinese food. Staff were courteous and helpful with local information. Location provides easy access to beachfront while maintaining quiet ambiance. Only minor note is room could be slightly larger. Overall great value for peaceful Sanur beach holiday.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'David Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.7,
            comment: 'Excellent boutique suite in relaxing Sanur! Perfect location for peaceful getaway. Suite is comfortable with good facilities and nice terrace. Hotel exudes charm with traditional Balinese touches. Sanur beach is fantastic for morning runs and evening strolls - calm water and beautiful sunrises. We appreciated the less commercialized atmosphere compared to other areas. Great restaurants along beachfront serving fresh seafood. Staff were friendly and arranged boat trip to nearby islands. Hotel pool and gardens are well-maintained. Great value for tranquil beach experience with authentic Balinese hospitality.',
            cleanliness: 4.7,
            accuracy: 4.7,
            communication: 4.7,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Karen White',
            userAvatar: null,
            rating: 4.5,
            comment: 'Nice boutique hotel suite in peaceful Sanur setting! We wanted quiet beach holiday and Sanur was perfect choice. Suite is comfortable with adequate space and amenities. Hotel has pleasant tropical atmosphere with friendly staff. Sanur beach is beautiful with safe swimming and stunning sunrise views. We enjoyed the relaxed pace and local cafes. Area feels more authentic with traditional markets nearby. Staff helped arrange cultural tours and temple visits. Only issue was occasional noise from adjacent rooms but generally quiet. Good value for relaxing Sanur stay away from tourist crowds.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Christopher Lee',
            userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
            rating: 4.6,
            comment: 'Comfortable boutique suite in charming Sanur! Great choice for peaceful beach vacation. Suite is well-equipped with comfortable furnishings and nice view. Hotel has character with traditional design and welcoming atmosphere. Sanur offers relaxing beach lifestyle - calm waters perfect for swimming and paddleboarding. We loved the beachfront promenade for cycling and people-watching. Local restaurants serve excellent food at reasonable prices. Staff were helpful and attentive. Hotel facilities including pool are nicely maintained. Only minor note is decor slightly dated but clean and functional. Good value Sanur accommodation.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-06-30').toISOString(),
            updatedAt: new Date('2024-06-30').toISOString(),
        },
        {
            propertyId: 97,
            carId: null,
            userId: null,
            userName: 'Barbara Martinez',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.5,
            comment: 'Pleasant boutique hotel suite in tranquil Sanur! Perfect for those seeking quieter Bali experience. Suite has comfortable bed and good amenities. Hotel grounds are lovely with tropical plants and flowers. Sanur beach is wonderful for relaxation - gentle waves and beautiful scenery. We appreciated the less hectic atmosphere and local character. Beachfront has variety of dining options with fresh seafood. Staff were friendly and helped with local recommendations. Only issue was air conditioning bit noisy but manageable. Overall good value for peaceful Sanur beach stay with authentic Balinese charm.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },

        // Property 99: Tropical House in Pererenan (7 reviews) - Mid-range
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Lauren Mitchell',
            userAvatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150',
            rating: 4.6,
            comment: 'Beautiful tropical house in quiet Pererenan! Perfect location for peaceful escape while still close to action. House is surrounded by rice fields creating serene atmosphere. We loved the open-air living concept with tropical garden. Pererenan is less touristy than Canggu but has great beach and surf. Short scooter ride to Canggu cafes and restaurants. House has comfortable bedrooms and well-equipped kitchen. Enjoyed morning coffees watching sunrise over rice paddies. Staff were helpful with recommendations. Only note is location requires transport to beaches. Great value for tranquil stay near Canggu.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.5,
            value: 4.7,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-08').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Daniel Brooks',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.5,
            comment: 'Nice tropical house in peaceful Pererenan area! Great for those wanting quiet location near Canggu buzz. House has authentic Balinese feel with modern comforts. Rice field views are beautiful and area is very tranquil. We enjoyed exploring Pererenan Beach which is less crowded than Canggu beaches. House kitchen is good for preparing meals and outdoor space is lovely. Short ride to Canggu for restaurants and nightlife. Staff responsive via WhatsApp. Minor issue with hot water but quickly fixed. Good value for spacious tropical house near Canggu action.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.4,
            value: 4.6,
            createdAt: new Date('2024-07-18').toISOString(),
            updatedAt: new Date('2024-07-18').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Ashley Cooper',
            userAvatar: null,
            rating: 4.7,
            comment: 'Lovely tropical house in serene Pererenan! Perfect balance between tranquility and accessibility. House has charming traditional design with comfortable furnishings. We loved the lush garden and rice field surroundings. Pererenan has relaxed vibe with local warungs and quiet beach. Easy scooter access to Canggu restaurants and beach clubs. House has good amenities including reliable wifi for remote work. Enjoyed peaceful mornings and exploring nearby rice paddies. Staff were helpful arranging transport. Only note is needs mosquito nets but repellent works. Excellent value for tropical house near Canggu.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.5,
            value: 4.7,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Joshua Turner',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.4,
            comment: 'Good tropical house in quiet Pererenan location! Great for experiencing local life away from tourist areas. House is spacious with nice outdoor living areas. Rice field setting is peaceful and authentic. Pererenan is developing but maintains village feel. We surfed at Pererenan Beach which is less crowded. Short ride to Canggu for cafes and restaurants. House has basic amenities though kitchen could be better equipped. Staff communication adequate but not always prompt. Minor maintenance issues but manageable. Decent value for those wanting peaceful location near Canggu with authentic Bali feel.',
            cleanliness: 4.4,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.3,
            value: 4.5,
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2024-06-15').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Megan Phillips',
            userAvatar: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=150',
            rating: 4.6,
            comment: 'Charming tropical house in tranquil Pererenan! Perfect for peaceful retreat with easy Canggu access. House has lovely tropical garden and rice field views. We appreciated the quiet environment after days exploring Bali. Pererenan maintains traditional character with local community feel. Beach is nice for sunset walks. Close enough to Canggu for restaurants and activities but far enough for peace. House is comfortable with good bedrooms. Staff helpful with scooter rental and recommendations. Only note is some insects due to rice field location. Great value for tropical house experience near Canggu.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.5,
            value: 4.7,
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Ryan Edwards',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.5,
            comment: 'Nice tropical house in peaceful Pererenan setting! Great for digital nomads wanting quiet workspace. House has good wifi and comfortable areas for working. Rice field views provide calming atmosphere. We balanced work with surfing at Pererenan Beach and exploring Canggu. House kitchen is functional for cooking. Area is authentic with local warungs nearby. Staff were friendly though response time varied. House could use some updates but clean and comfortable. Minor issue with water pressure. Good value for longer stay wanting peaceful environment near Canggu action.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.4,
            value: 4.6,
            createdAt: new Date('2024-07-05').toISOString(),
            updatedAt: new Date('2024-07-05').toISOString(),
        },
        {
            propertyId: 99,
            carId: null,
            userId: null,
            userName: 'Nicole Baker',
            userAvatar: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=150',
            rating: 4.6,
            comment: 'Comfortable tropical house in serene Pererenan! Perfect location for experiencing local Bali life. House has authentic design with modern amenities. We loved the peaceful rice field setting and tropical garden. Pererenan is quieter alternative to Canggu with its own charm. Beach is nice for walks and swimming. Easy access to Canggu for dining and shopping. House is spacious with good outdoor areas. Staff were helpful arranging activities. Only note is transport needed for most places. Excellent value for tropical house stay with authentic atmosphere near Canggu conveniences.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.5,
            value: 4.7,
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },

        // Property 100: Beachside Condo in Jimbaran (8 reviews) - Mid-range
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Amanda Foster',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.6,
            comment: 'Great beachside condo in beautiful Jimbaran! Perfect location near famous seafood restaurants on the beach. Condo is modern and well-maintained with comfortable furnishings. We loved walking to beach for sunset dinners - fresh seafood grilled right on sand is unforgettable. Jimbaran Bay is stunning with calm water perfect for swimming. Area is more laid-back than Seminyak with local character. Condo building has nice pool and security. Staff were friendly and helpful. Only minor issue was occasional noise from nearby construction. Excellent value for beachside living in Jimbaran.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Brandon Clark',
            userAvatar: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=150',
            rating: 4.5,
            comment: 'Nice beachside condo in lovely Jimbaran area! Great for beach lovers and seafood enthusiasts. Condo is comfortable with good amenities and balcony with partial ocean view. Jimbaran Beach is beautiful with gentle waves and spectacular sunsets. We enjoyed daily beach walks and trying different seafood warungs. Area is quieter than other beach areas but still has good restaurants. Condo complex has pleasant pool area. Staff communication was good. Minor issue with wifi speed but manageable. Good value for beachside accommodation in Jimbaran with authentic local atmosphere.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-07-22').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Catherine Young',
            userAvatar: null,
            rating: 4.7,
            comment: 'Lovely beachside condo in picturesque Jimbaran! Perfect location for beach holiday with famous seafood dining. Condo is well-appointed with modern kitchen and comfortable living space. We loved proximity to beach - walked there daily for swimming and sunset watching. Jimbaran fish market is fascinating to explore. Area has good mix of local warungs and upscale restaurants. Condo building is secure with helpful staff. Enjoyed the relaxed pace compared to busier areas. Only note is parking can be tight. Excellent value for beachside living in beautiful Jimbaran Bay area.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-08-18').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Derek Howard',
            userAvatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150',
            rating: 4.4,
            comment: 'Good beachside condo in Jimbaran location! Nice base for exploring southern Bali beaches. Condo is functional with adequate amenities. Jimbaran Beach is beautiful for swimming and famous for sunset seafood dinners. We tried multiple beach restaurants and all were excellent. Area is less developed than Seminyak with more traditional feel. Condo complex has pool though small. Staff were friendly though not always available. Minor maintenance issues but addressed. Air conditioning works well. Decent value for beachside accommodation in Jimbaran with authentic local atmosphere and great seafood.',
            cleanliness: 4.4,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.5,
            value: 4.5,
            createdAt: new Date('2024-06-10').toISOString(),
            updatedAt: new Date('2024-06-10').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Emily Harrison',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 4.6,
            comment: 'Comfortable beachside condo in charming Jimbaran! Great location for beach and seafood lovers. Condo is well-maintained with modern fixtures and nice balcony. We loved the peaceful beach atmosphere and watching fishing boats. Jimbaran seafood restaurants are incredible - fresh fish grilled to perfection while watching sunset. Area has authentic local character with traditional markets. Condo building has good facilities and security. Staff were helpful with recommendations. Only minor issue was occasional hot water problems. Excellent value for beachside stay in Jimbaran with famous dining and beautiful bay.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Frank Mitchell',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
            rating: 4.5,
            comment: 'Nice beachside condo in relaxing Jimbaran setting! Perfect for peaceful beach holiday. Condo has comfortable layout with good kitchen facilities. Jimbaran Bay is stunning with calm water ideal for families. We enjoyed the less touristy atmosphere and local feel. Beach seafood dining is highlight - so many great restaurants to try. Area is convenient to airport and Uluwatu attractions. Condo complex pool is pleasant for afternoon relaxation. Staff communication adequate. Minor issue with cleanliness upon arrival but resolved. Good value for beachside accommodation in beautiful Jimbaran with authentic character.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-07-12').toISOString(),
            updatedAt: new Date('2024-07-12').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Grace Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.6,
            comment: 'Pleasant beachside condo in lovely Jimbaran! Great location for beach access and seafood dining. Condo is modern with comfortable furnishings and nice views. We loved the proximity to famous Jimbaran fish market and beach restaurants. Sunset dinners on beach were memorable experiences. Area is quieter than Seminyak with more traditional Balinese atmosphere. Condo building has good security and amenities. Staff were friendly and helpful. Only note is street noise occasionally but manageable. Excellent value for beachside living in Jimbaran with beautiful bay and incredible seafood options.',
            cleanliness: 4.6,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            propertyId: 100,
            carId: null,
            userId: null,
            userName: 'Henry Rodriguez',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.5,
            comment: 'Solid beachside condo in scenic Jimbaran! Perfect base for exploring southern Bali attractions. Condo is well-equipped with modern amenities and comfortable beds. Jimbaran Beach is beautiful for swimming and walking. We loved the seafood restaurant scene - fresh catch prepared beachside is amazing. Area maintains local character with traditional markets and temples nearby. Condo complex has nice pool and grounds. Staff were responsive and helpful. Minor issue with parking availability. Good value for beachside accommodation in Jimbaran with authentic atmosphere, great food, and beautiful bay views.',
            cleanliness: 4.5,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-06-28').toISOString(),
            updatedAt: new Date('2024-06-28').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder for Bali properties completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});