import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // Property 78: Luxurious Penthouse in SCBD, Jakarta - 8 reviews
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'James Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 5.0,
            comment: 'Absolutely stunning penthouse in the heart of SCBD! The panoramic city views are breathtaking, especially at night. The interior design is impeccable with high-end furnishings and smart home features. Location is perfect - walking distance to Plaza Senayan and Pacific Place. The building security is top-notch and the concierge service was incredibly helpful. Worth every rupiah for a luxury stay in Jakarta.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Dewi Kartika',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.9,
            comment: 'Pengalaman menginap yang luar biasa di penthouse SCBD ini. Fasilitas sangat lengkap dengan kolam renang infinity yang menghadap skyline Jakarta. Dapur modern dengan peralatan Miele, kamar mandi seperti spa hotel bintang lima. Lokasinya strategis dekat dengan kantor dan pusat perbelanjaan. Host sangat responsif dan profesional. Highly recommended untuk business traveler atau special occasion.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Marco Rossi',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.8,
            comment: 'Spectacular penthouse with world-class amenities. The 360-degree view of SCBD and Jakarta skyline is simply magnificent. Master bedroom with ensuite bathroom featuring rain shower and soaking tub. Smart home automation makes everything convenient. Close to embassies and international restaurants. Perfect for extended business stays. Only minor feedback - would appreciate more international TV channels.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Sophie Laurent',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 5.0,
            comment: 'This penthouse exceeded all expectations! Luxurious living space with floor-to-ceiling windows offering stunning SCBD views. The kitchen is a chef dream with premium appliances and marble countertops. Located in prestigious area with easy access to shopping malls, fine dining, and business district. Excellent wifi speed for remote work. Host provided detailed arrival instructions and check-in was seamless. Will definitely book again!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Ahmed Hassan',
            userAvatar: null,
            rating: 4.7,
            comment: 'Premium accommodation in Jakarta best business district. The penthouse features elegant contemporary design with high-quality finishes throughout. Walking distance to major offices and luxury hotels. Security system is excellent with 24/7 reception. Enjoyed the private terrace with outdoor seating. Property manager was very accommodating and helped arrange airport transfer. Great value for corporate housing in SCBD area.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Min-joo Park',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.9,
            comment: 'Absolutely loved staying in this SCBD penthouse! The space is incredibly spacious and beautifully designed with attention to every detail. Smart home technology controls lighting, temperature, and entertainment systems. Neighborhood is very safe and convenient with restaurants, cafes, and shopping within walking distance. Master bedroom has amazing city views. Host communication was excellent and provided local recommendations. Perfect for luxury travelers!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-04-12').toISOString(),
            updatedAt: new Date('2024-04-12').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Budi Santoso',
            userAvatar: null,
            rating: 4.8,
            comment: 'Penthouse yang sangat mewah dengan view Jakarta yang spektakuler. Interior design modern minimalis dengan furniture berkualitas tinggi. Lokasi di SCBD sangat strategis untuk business meeting dan dekat dengan restaurant fine dining. Building facilities termasuk gym dan swimming pool sangat baik. Host sangat helpful dan professional. Recommended untuk tamu corporate atau family celebration yang menginginkan pengalaman premium stay di Jakarta.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            propertyId: 78,
            carId: null,
            userId: null,
            userName: 'Emma Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 5.0,
            comment: 'Outstanding penthouse that truly represents luxury living in Jakarta! The SCBD location is unbeatable - surrounded by international restaurants, shopping, and entertainment. Interior is magazine-worthy with designer furniture and art pieces. Kitchen fully equipped with premium appliances including wine fridge. Bathrooms feature rainfall showers and premium toiletries. Building amenities include valet parking and 24-hour security. Host was incredibly responsive. Highly recommend for discerning travelers!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-05-20').toISOString(),
            updatedAt: new Date('2024-05-20').toISOString(),
        },

        // Property 79: Modern Apartment in Menteng, Jakarta - 6 reviews
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'Sarah Mitchell',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.6,
            comment: 'Great apartment in the historic Menteng neighborhood. The location is fantastic - walking distance to traditional Indonesian restaurants and cafes. Apartment is clean and modern with comfortable furniture. Really enjoyed the balcony with tree-lined street views. Area is quiet and residential, perfect for relaxing after busy days exploring Jakarta. Host provided helpful tips about local transportation and nearby attractions. Good value for the price.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'Yuki Tanaka',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.5,
            comment: 'Comfortable modern apartment in Menteng area. Location is excellent for experiencing local Jakarta culture - surrounded by heritage buildings and traditional warungs. Apartment has good natural lighting and well-equipped kitchen. Wifi speed was sufficient for work. Appreciated the air conditioning in every room. Walking distance to minimarket and local food spots. Host was friendly and check-in process was smooth. Recommended for solo travelers or couples.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'Siti Aminah',
            userAvatar: null,
            rating: 4.7,
            comment: 'Apartemen yang nyaman di lokasi strategis Menteng. Design interior modern dengan perabotan lengkap. Sangat dekat dengan Taman Suropati dan area kuliner Menteng. Kamar tidur cukup luas dengan tempat tidur yang nyaman. Dapur dilengkapi dengan kompor dan kulkas. Area parkir tersedia di basement. Host responsif dan membantu dengan informasi sekitar. Cocok untuk stay jangka pendek maupun panjang di Jakarta pusat.',
            cleanliness: 4.7,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'Wei Chen',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            rating: 4.4,
            comment: 'Nice apartment in central Menteng location. The neighborhood has character with old trees and heritage architecture. Apartment is well-maintained with modern amenities including washing machine. Living room has comfortable sofa and smart TV. Close to several good restaurants and coffee shops. Building security was professional. Only minor issue was occasional street noise during peak hours. Overall good experience and reasonable price for the location.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'Fatima Al-Rashid',
            userAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150',
            rating: 4.6,
            comment: 'Enjoyed my stay at this Menteng apartment. Location is ideal for exploring central Jakarta with easy access to museums and cultural sites. Apartment has clean minimalist design with everything you need. Kitchen facilities allowed me to prepare simple meals. Bedroom was peaceful with blackout curtains. Appreciated the fast wifi for remote work. Host provided clear instructions and was available for questions. Good option for business or leisure travelers seeking authentic Jakarta experience.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-05-08').toISOString(),
        },
        {
            propertyId: 79,
            carId: null,
            userId: null,
            userName: 'David Rodriguez',
            userAvatar: null,
            rating: 4.5,
            comment: 'Solid apartment in the heart of Menteng. The area has lots of character with tree-lined streets and local eateries. Apartment is spacious enough for comfortable living with functional layout. All basic amenities provided including iron and hair dryer. Building has elevator and secure parking. Walking distance to convenience stores and grab pick-up points. Host communication was prompt. Great value compared to hotels in similar location. Would stay again for longer Jakarta visits.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-05-25').toISOString(),
            updatedAt: new Date('2024-05-25').toISOString(),
        },

        // Property 80: Elegant Villa in Kemang, Jakarta - 9 reviews
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Isabella Martinez',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
            rating: 4.9,
            comment: 'Absolutely beautiful villa in trendy Kemang area! The property is spacious with elegant tropical design and private swimming pool. Living areas are beautifully decorated with Indonesian art pieces. Bedrooms are luxurious with ensuite bathrooms. Kitchen is fully equipped for serious cooking. The garden is lush and well-maintained - perfect for morning coffee. Location is fantastic with walking distance to Kemang hip restaurants, cafes, and boutiques. Host was exceptional in every way. Highly recommended!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Ravi Sharma',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.8,
            comment: 'Stunning villa that exceeded expectations! The Kemang location is perfect - close to international restaurants, bars, and shopping. Villa features traditional Javanese architecture with modern luxury touches. Pool area is private and beautifully landscaped. Bedrooms are spacious with comfortable king beds. Living room has high ceilings and natural light. Staff was helpful and discreet. Perfect for family gatherings or business entertainment. Excellent value for luxury villa in Jakarta.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Amelia Foster',
            userAvatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150',
            rating: 5.0,
            comment: 'This Kemang villa is a true gem! Beautifully designed with attention to detail in every corner. The pool is amazing - we spent hours there with family. Indoor-outdoor living space creates wonderful flow. Kitchen has everything including espresso machine. Kemang neighborhood is vibrant with excellent dining options. Walking distance to several popular spots. Villa staff provided great service. Host was responsive and accommodating. Perfect for special occasions or extended family stays. Cannot recommend enough!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Taufik Hidayat',
            userAvatar: null,
            rating: 4.7,
            comment: 'Villa yang sangat indah dengan design elegant di Kemang. Kolam renang private dengan landscaping yang bagus. Ruang tamu luas dengan furniture berkualitas. Kamar tidur nyaman dengan AC dan kamar mandi ensuite. Dapur lengkap dengan peralatan modern. Lokasi strategis dekat dengan restaurant dan café terkenal di Kemang. Staff helpful dan professional. Cocok untuk family gathering atau corporate retreat. Recommended untuk yang mencari privacy dan luxury di Jakarta selatan.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Oliver Bennett',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.9,
            comment: 'Magnificent villa in prime Kemang location! The property combines traditional Indonesian charm with modern luxury. Pool area is resort-quality with sun loungers and outdoor dining. Interior features high-quality furnishings and tasteful decor. Every bedroom has its own character and ensuite bathroom. Kitchen is commercial-grade perfect for catering. Security is excellent with gated entrance. Neighborhood is expat-friendly with international restaurants. Host provided excellent service throughout. Ideal for luxury family vacation or special events.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Nadia Putri',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.8,
            comment: 'Pengalaman menginap yang luar biasa di villa Kemang ini! Design interior sangat elegant dengan sentuhan traditional Indonesia. Pool area private dan sangat terawat. Setiap kamar dilengkapi dengan AC dan bathroom yang luxurious. Living room spacious dengan entertainment system yang lengkap. Lokasi di jantung Kemang dekat dengan tempat makan dan shopping. Staff sangat attentive dan helpful. Perfect untuk celebration atau long stay dengan family. Highly recommended!',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Michael Chen',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.9,
            comment: 'Exceptional villa that offers true luxury living in Kemang. Architecture beautifully blends colonial style with tropical elements. Pool is heated and perfectly maintained. Garden has mature trees providing natural privacy. Bedrooms are hotel-quality with premium linens and pillows. Living spaces are perfect for entertaining. Smart home features include lighting and security system. Kemang location offers best restaurants and nightlife in Jakarta. Host was professional and accommodating. Worth every rupiah for special stays.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-05-03').toISOString(),
            updatedAt: new Date('2024-05-03').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Charlotte Anderson',
            userAvatar: null,
            rating: 5.0,
            comment: 'This Kemang villa is absolutely perfect in every way! From the moment we arrived, everything exceeded expectations. The villa is spacious yet feels cozy with beautiful Indonesian touches throughout. Pool area is like private resort. Kitchen is chef-worthy with premium appliances. Each bedroom suite feels like luxury hotel room. Location cannot be better - best restaurants, cafes, and shopping in Kemang within walking distance. Host went above and beyond with local recommendations. Perfect for family reunions or milestone celebrations!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        {
            propertyId: 80,
            carId: null,
            userId: null,
            userName: 'Hiroshi Yamamoto',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            rating: 4.8,
            comment: 'Outstanding villa in prestigious Kemang neighborhood. Property features elegant design with high-quality finishes. Swimming pool area is beautifully landscaped with tropical plants. Living and dining areas are spacious enough for large gatherings. Bedrooms offer privacy with ensuite facilities. Modern kitchen fully equipped including dishwasher. Location is ideal with easy access to Jakarta best dining and entertainment. Security is excellent with 24-hour guard. Host communication was clear and helpful. Highly recommended for discerning travelers seeking luxury villa experience.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-06-12').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },

        // Property 81: Boutique Hotel Suite in Thamrin, Jakarta - 7 reviews
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Alexandra White',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.6,
            comment: 'Lovely boutique hotel suite in central Thamrin location. The suite is well-designed with modern amenities and comfortable furnishings. Bedroom has plush bedding and blackout curtains. Bathroom features rain shower and premium toiletries. Living area has work desk perfect for business travelers. Location is unbeatable - walking distance to Grand Indonesia mall and Bundaran HI. Hotel staff is professional and courteous. Breakfast options are good with Indonesian and Western choices. Great value for central Jakarta stay.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Kenji Suzuki',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.5,
            comment: 'Comfortable boutique suite in prime Thamrin area. Room is spacious with separate living area and bedroom. Modern bathroom with good water pressure. Mini kitchen with coffee maker and minibar. Wifi speed excellent for remote work. Location is perfect for business - near embassies and corporate offices. Walking distance to MRT station and shopping malls. Hotel facilities include small gym and business center. Staff helpful with local recommendations. Good choice for extended business stays in Jakarta.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Rina Wijaya',
            userAvatar: null,
            rating: 4.7,
            comment: 'Suite yang nyaman dengan lokasi strategis di Thamrin. Design interior modern dengan sentuhan boutique. Kamar tidur tenang dengan bed yang comfortable. Bathroom lengkap dengan amenities berkualitas. Living area cukup luas untuk work atau relax. Lokasi sangat dekat dengan Grand Indonesia, Plaza Indonesia, dan Hotel Indonesia roundabout. Staff hotel ramah dan helpful. Breakfast buffet varied dengan menu local dan international. Recommended untuk business traveler atau tourist yang menginginkan central location.',
            cleanliness: 4.7,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Thomas Schmidt',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.4,
            comment: 'Nice boutique hotel suite in the heart of Thamrin business district. Suite layout is functional with good use of space. Bedroom comfortable with adequate storage. Bathroom clean with modern fixtures. Living area has sofa and work desk. Location is excellent for meetings and shopping. Walking distance to major malls and restaurants. Hotel service is efficient though sometimes slow during peak hours. Breakfast is decent with good coffee. Overall good value for Thamrin location and suitable for business stays.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Maria Santos',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 4.6,
            comment: 'Enjoyed staying at this boutique suite in Thamrin. Room is well-appointed with contemporary design and comfortable furnishings. Bedroom has good air conditioning and quiet despite central location. Bathroom spacious with separate shower. Kitchenette useful for preparing light meals. Building security is good with key card access. Perfect location for exploring Jakarta - near Monas, museums, and shopping districts. Hotel staff was friendly and accommodating. Good breakfast spread. Recommended for both leisure and business travelers.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Adrian Tan',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.5,
            comment: 'Solid boutique hotel suite with excellent Thamrin location. Suite offers good space with separate sleeping and living areas. Amenities include smart TV, safe, and minibar. Bathroom well-maintained with hot water and toiletries. Location is incredibly convenient - walking to Grand Indonesia, Plaza Indonesia, and MRT station. Easy grab access for exploring Jakarta. Hotel staff professional and helpful. Breakfast has good variety. WiFi reliable for work. Great option for business trips or short city breaks.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.9,
            value: 4.5,
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-05-15').toISOString(),
        },
        {
            propertyId: 81,
            carId: null,
            userId: null,
            userName: 'Lisa Wagner',
            userAvatar: null,
            rating: 4.7,
            comment: 'Very pleasant stay at this Thamrin boutique suite. Room is tastefully decorated with modern amenities and comfortable furniture. Bedroom quiet with blackout curtains ensuring good sleep. Living area perfect for relaxing or working. Bathroom clean with good shower pressure. Kitchenette has essentials including refrigerator and electric kettle. Location could not be better for shopping and dining. Close to iconic landmarks. Hotel service attentive and responsive. Breakfast quality good. Excellent value for central Jakarta accommodation.',
            cleanliness: 4.7,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-06-08').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },

        // Property 82: Contemporary House in Pondok Indah, Jakarta - 8 reviews
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Rachel Green',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 4.7,
            comment: 'Beautiful contemporary house in upscale Pondok Indah neighborhood. The house features modern architecture with large windows and open floor plan. Living areas are spacious and well-decorated. Kitchen is fully equipped with quality appliances. Bedrooms are comfortable with ensuite bathrooms. Garden is well-maintained with nice outdoor seating. Location is excellent - near Pondok Indah Mall and international schools. Area is safe and quiet, perfect for families. Host was responsive and helpful. Great value for luxury house rental in South Jakarta.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Arjun Patel',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.6,
            comment: 'Lovely house in prestigious Pondok Indah area. Property is modern with clean lines and contemporary furnishings. Living room has high ceilings and plenty of natural light. Master bedroom spacious with walk-in closet. All bedrooms have air conditioning and quality mattresses. Kitchen modern with dining area. Garden provides nice private outdoor space. Location is family-friendly with easy access to malls, restaurants, and schools. Security in neighborhood is excellent. Host provided clear instructions. Good choice for expat families or extended stays.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Patricia Wong',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.8,
            comment: 'Fantastic contemporary house perfect for family living in Jakarta. The house has wonderful flow between indoor and outdoor spaces. Kitchen is well-designed with breakfast bar and modern appliances. Bedrooms are generously sized with good storage. Bathrooms are contemporary with rainfall showers. Living areas comfortable for entertaining. Garden has covered terrace. Pondok Indah location is ideal - safe neighborhood with excellent amenities nearby. Walking distance to shopping and dining. Host was excellent. Highly recommended for families relocating to Jakarta.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Ahmad Rizki',
            userAvatar: null,
            rating: 4.5,
            comment: 'Rumah contemporary yang bagus di Pondok Indah. Design modern dengan ruang yang luas dan layout yang functional. Living room dan dining area open space dengan AC yang powerful. Kamar tidur nyaman dengan bed berkualitas. Dapur lengkap dengan peralatan modern. Garden cukup luas untuk outdoor activity. Lokasi sangat strategis dekat dengan PIM dan JIS. Neighborhood aman dan nyaman untuk keluarga. Host helpful dan responsive. Recommended untuk expat family atau Indonesian family yang mencari house di area premium.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Sophie Dubois',
            userAvatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150',
            rating: 4.7,
            comment: 'Wonderful house in prime Pondok Indah location. Contemporary design with quality finishes throughout. Open living spaces perfect for family life. Kitchen has all modern conveniences including dishwasher. Bedrooms comfortable with good closet space. Garden well-maintained with lawn and plants. Area is very safe and convenient - close to international schools, hospitals, and shopping centers. Great expat community. Host was professional and accommodating. Perfect for families needing spacious comfortable home in South Jakarta.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Daniel Park',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.6,
            comment: 'Excellent contemporary house in upscale Pondok Indah area. House is well-maintained with modern furnishings and decor. Living and dining areas spacious enough for entertaining. Kitchen fully equipped with quality appliances. Bedrooms comfortable with ensuite bathrooms. Garden provides nice outdoor space. Location is fantastic - near PIM, restaurants, and international schools. Neighborhood is secure and family-friendly. Wifi reliable for remote work. Host communication was good. Great option for expat families or long-term corporate housing.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-05-02').toISOString(),
            updatedAt: new Date('2024-05-02').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Maya Putri',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.8,
            comment: 'Rumah yang sangat nyaman dan modern di Pondok Indah. Interior design contemporary dengan furniture berkualitas. Living room luas dengan sofa yang comfortable. Dapur dilengkapi dengan appliances lengkap. Setiap bedroom ada ensuite bathroom. Garden terawat dengan baik. Lokasi premium dekat dengan segala fasilitas - mall, restaurant, school, hospital. Area sangat aman dan tenang. Perfect untuk family dengan anak. Host very responsive dan helpful. Highly recommended untuk yang mencari quality house di South Jakarta.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        {
            propertyId: 82,
            carId: null,
            userId: null,
            userName: 'Robert Johnson',
            userAvatar: null,
            rating: 4.7,
            comment: 'Great contemporary house in excellent Pondok Indah location. Property is spacious with modern amenities throughout. Living areas bright and welcoming. Kitchen well-equipped for cooking. Bedrooms comfortable with good air conditioning. Bathrooms modern and clean. Garden provides pleasant outdoor area. Neighborhood is safe, quiet, and convenient. Close proximity to international schools and shopping. Perfect for expatriate families. Host was helpful and responsive to questions. House met all our needs for comfortable family living in Jakarta. Would recommend and stay again.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2024-06-15').toISOString(),
        },

        // Property 84: Cozy Apartment in Senopati, Jakarta - 6 reviews
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'Emily Parker',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.5,
            comment: 'Charming cozy apartment in the heart of Senopati. Perfect location for foodies - surrounded by Jakarta best restaurants and cafes. Apartment is clean and well-maintained with comfortable furnishings. Bedroom has good bed and quiet despite central location. Kitchen has basics for simple cooking. Living area compact but functional. Loved being able to walk to dinner spots. Building has good security. Host was responsive and provided helpful neighborhood tips. Great value for trendy Senopati location. Ideal for solo travelers or couples.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'Lucas Silva',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.4,
            comment: 'Nice cozy apartment in vibrant Senopati area. Location is unbeatable - walking distance to numerous restaurants, bars, and cafes. Apartment is compact but has everything needed for comfortable stay. Bedroom comfortable with good AC. Bathroom clean with hot shower. Kitchen suitable for breakfast and light meals. Living space has sofa and TV. Building amenities include parking and elevator. Neighborhood is lively especially evenings and weekends. Host provided clear check-in instructions. Good choice for experiencing Jakarta nightlife scene.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'Dini Lestari',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 4.6,
            comment: 'Apartemen yang cozy dan nyaman di Senopati. Lokasi sangat strategis di tengah culinary district Jakarta. Walking distance ke banyak restaurant dan café terkenal. Unit compact tapi functional dengan furniture lengkap. Bedroom comfortable dengan tempat tidur yang enak. Kitchen equipped untuk masak simple. Living area cukup untuk relax. Building security bagus dengan CCTV. Host responsif dan helpful. Perfect untuk young professional atau couple yang suka foodie scene. Value for money di area premium Senopati.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'James Wilson',
            userAvatar: null,
            rating: 4.3,
            comment: 'Decent cozy apartment in popular Senopati district. Unit is small but efficiently designed. Bedroom adequate with comfortable bed. Bathroom functional with reasonable water pressure. Kitchenette has microwave, fridge, and hot plate. Living area has small sofa and workspace. Best feature is location - surrounded by dining and entertainment options. Easy grab access. Building is secure with friendly staff. WiFi good for work. Host communication adequate. Suitable for short stays or solo travelers who want central location.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.8,
            value: 4.4,
            createdAt: new Date('2024-04-22').toISOString(),
            updatedAt: new Date('2024-04-22').toISOString(),
        },
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'Anna Kowalski',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
            rating: 4.5,
            comment: 'Lovely cozy apartment perfectly located in trendy Senopati. The apartment is compact but thoughtfully arranged with all essentials. Bedroom comfortable with blackout curtains for good sleep. Bathroom clean and modern. Kitchen has necessary appliances for basic cooking. Living area cozy with comfortable seating. Location is fantastic - walking to many restaurants, coffee shops, and bars. Neighborhood has great energy. Building well-maintained with security. Host was helpful with recommendations. Great value for being in heart of Jakarta dining scene.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-05-18').toISOString(),
        },
        {
            propertyId: 84,
            carId: null,
            userId: null,
            userName: 'Kevin Nguyen',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            rating: 4.4,
            comment: 'Good cozy apartment in prime Senopati location. Unit is small but clean and comfortable. Bedroom has decent bed and storage. Bathroom modern with good shower. Kitchen compact with essential appliances. Living space adequate for one or two people. Location is the highlight - surrounded by Jakarta best restaurants and nightlife. Walking distance to everything. Building has elevator and parking. WiFi reliable. Host responsive. Ideal for foodies and nightlife enthusiasts. Fair price for the location and convenience in Senopati area.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-06-10').toISOString(),
            updatedAt: new Date('2024-06-10').toISOString(),
        },

        // Property 85: Executive Hotel Suite in Mega Kuningan, Jakarta - 7 reviews
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Victoria Hamilton',
            userAvatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150',
            rating: 4.6,
            comment: 'Excellent executive suite in prime Mega Kuningan business district. Suite is spacious with separate bedroom and living area. Bedroom comfortable with quality linens and good mattress. Living room has work desk perfect for business needs. Bathroom modern with rain shower and amenities. Kitchen has coffee maker and minibar. Location is perfect for corporate travelers - walking to major offices and embassies. Hotel facilities include gym and business center. Staff professional and helpful. Breakfast buffet has good variety. Great choice for extended business stays.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Richard Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.5,
            comment: 'Very good executive suite in Mega Kuningan area. Suite layout is functional with clear separation between work and rest areas. Bedroom quiet with blackout curtains. Bathroom clean with good water pressure. Living area has ergonomic desk and comfortable sofa. WiFi speed excellent for video conferences. Location ideal for business - near embassies, corporate offices, and restaurants. Hotel service efficient and professional. Breakfast options adequate. Gym facilities basic but functional. Solid choice for business travelers needing apartment-style accommodation.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Stephanie Lee',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 4.7,
            comment: 'Impressive executive suite perfectly suited for business stays in Mega Kuningan. Suite is well-appointed with modern furnishings and professional atmosphere. Bedroom comfortable ensuring good rest. Living room spacious with large work area and meeting space. Bathroom features premium fixtures. Kitchenette useful for preparing light meals. Location could not be better - central business district with easy access to offices and dining. Hotel amenities include pool and gym. Staff attentive and responsive. Breakfast quality good. Highly recommended for corporate travelers.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Rudi Hartono',
            userAvatar: null,
            rating: 4.4,
            comment: 'Suite yang bagus untuk business stay di Mega Kuningan. Layout functional dengan bedroom terpisah dari living area. Kamar tidur nyaman dengan AC yang dingin. Bathroom clean dengan shower yang bagus. Living room cukup luas untuk work atau meeting. Kitchenette dengan basic facilities. Lokasi strategis di business district dekat dengan kantor dan restaurant. Hotel facilities termasuk gym dan pool. Staff helpful dan professional. Breakfast buffet varied. Good option untuk corporate traveler yang butuh longer stay.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Catherine Moore',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.6,
            comment: 'Wonderful executive suite in prime Mega Kuningan location. Suite offers excellent space with dedicated work area. Bedroom restful with comfortable bedding. Bathroom modern and well-maintained. Living room perfect for entertaining clients or working. Kitchen has essentials including fridge and microwave. Location is fantastic for business - surrounded by corporate offices and international restaurants. Hotel staff professional and accommodating. Gym well-equipped. Breakfast has international options. WiFi reliable. Great value for extended business stays in Jakarta.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Marcus Weber',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.5,
            comment: 'Good executive suite suited for business professionals in Mega Kuningan. Suite is well-designed with clear functional zones. Bedroom comfortable with quality mattress and pillows. Bathroom clean with modern amenities. Living area has work desk and dining table. Kitchenette adequately equipped. Location is perfect - central business district with everything accessible. Hotel facilities include fitness center and restaurant. Staff courteous and helpful. Breakfast buffet decent variety. WiFi strong throughout suite. Solid choice for corporate housing or extended business trips.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        {
            propertyId: 85,
            carId: null,
            userId: null,
            userName: 'Jennifer Martinez',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.6,
            comment: 'Excellent executive suite perfect for business stays in Mega Kuningan. Suite is spacious with separate sleeping and working areas. Bedroom quiet and comfortable. Bathroom well-appointed with good amenities. Living room has ergonomic workspace and entertainment area. Kitchenette practical for preparing breakfast. Location is ideal - heart of business district near embassies and offices. Hotel service is professional. Gym facilities adequate. Breakfast offers good selection. WiFi reliable for remote work. Highly recommended for corporate travelers seeking comfort and convenience.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-06-18').toISOString(),
        },

        // Property 86: Spacious Villa in Pantai Indah Kapuk, Jakarta - 9 reviews
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Benjamin Clark',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.9,
            comment: 'Absolutely stunning villa in exclusive PIK area! The property is magnificent with spacious rooms and beautiful architecture. Living areas are luxurious with high ceilings and premium furnishings. Master bedroom suite is like five-star hotel. Kitchen is fully equipped for serious cooking. Pool area is resort-quality with tropical landscaping. PIK location offers beach access, golf courses, and international restaurants. Perfect for family vacation or entertaining. Security excellent with gated community. Host was exceptional. Worth every penny for luxury villa experience.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Olivia Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
            rating: 4.8,
            comment: 'Magnificent spacious villa perfect for large families or groups in PIK. Villa features contemporary tropical design with attention to detail. Living spaces are generous and beautifully decorated. Bedrooms are comfortable with ensuite bathrooms. Kitchen has commercial-grade appliances. Pool and garden area are exceptional - perfect for relaxing and entertaining. PIK neighborhood is family-friendly with beaches, shopping, and dining nearby. Security is top-notch. Staff service was excellent. Host provided great communication. Highly recommended for special occasions or extended family stays.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Hendra Wijaya',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 5.0,
            comment: 'Villa yang luar biasa di PIK dengan design modern tropical. Space sangat luas cocok untuk family gathering besar. Setiap room beautifully designed dengan furniture premium. Master bedroom seperti presidential suite dengan bathroom yang luxurious. Kitchen lengkap dengan appliances high-end. Pool area seperti resort dengan landscaping yang indah. PIK location excellent dengan access ke beach, golf, dan restaurant international. Security 24 jam dengan gated community. Host sangat professional dan attentive. Perfect untuk special event atau long stay luxury.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Grace Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.9,
            comment: 'Outstanding villa that exceeded all expectations in PIK! The property is absolutely beautiful with sophisticated design throughout. Living and dining areas perfect for large gatherings. Every bedroom is spacious with luxury amenities. Kitchen is chef-quality with premium appliances. Pool area is stunning with outdoor living space. PIK location offers everything - beaches, restaurants, shopping, golf. Neighborhood is safe and upscale. Villa staff provided excellent service. Host was responsive and helpful. Perfect for milestone celebrations or luxury family vacation.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'William Davis',
            userAvatar: null,
            rating: 4.7,
            comment: 'Impressive spacious villa in prestigious PIK area. Property features modern architecture with high-end finishes. Living spaces are generous and well-appointed. Bedrooms comfortable with quality bedding. Bathrooms are luxurious with modern fixtures. Kitchen fully equipped for entertaining. Pool and garden beautifully maintained. PIK location convenient with nearby amenities and beach access. Security excellent in gated community. Villa staff helpful. Host communication good. Great option for families or groups seeking luxury accommodation in North Jakarta.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-04-02').toISOString(),
            updatedAt: new Date('2024-04-02').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Sophia Martinez',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 4.9,
            comment: 'Absolutely gorgeous villa perfect for luxury living in PIK! The space is incredibly generous with beautiful contemporary design. Living areas flow seamlessly to outdoor spaces. Bedrooms are hotel-quality with ensuite bathrooms. Kitchen has everything needed for gourmet cooking. Pool area is resort-standard with lounging areas. PIK neighborhood is fantastic - beaches, dining, shopping all nearby. Villa is in secure gated community. Staff service exceptional. Host was wonderful throughout. Perfect for special celebrations or extended family stays. Highly recommended!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Indra Kusuma',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            rating: 4.8,
            comment: 'Villa yang spectacular di PIK dengan space yang sangat luas. Design modern dengan tropical touch. Setiap corner beautifully decorated. Living dan dining area perfect untuk host gathering. Bedrooms spacious dengan ensuite bathroom yang luxurious. Kitchen commercial-grade dengan appliances lengkap. Pool dan garden area seperti private resort. PIK location excellent dengan beach access, golf course, dan restaurant international. Security top-notch di gated community. Staff very helpful. Host professional. Recommended untuk luxury family stay atau special event.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-05-18').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Alexander Wright',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 4.9,
            comment: 'Exceptional villa offering ultimate luxury in PIK! Property is magnificently designed with premium finishes throughout. Living spaces are enormous and elegantly furnished. Master suite is palatial with spa-like bathroom. Additional bedrooms equally impressive. Kitchen is professional-grade. Pool area rivals five-star resorts with beautiful landscaping. PIK location provides beach lifestyle with modern conveniences. Neighborhood secure and upscale. Villa staff attentive and professional. Host communication excellent. Perfect for discerning travelers seeking luxury villa experience. Worth every rupiah!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-06-05').toISOString(),
            updatedAt: new Date('2024-06-05').toISOString(),
        },
        {
            propertyId: 86,
            carId: null,
            userId: null,
            userName: 'Isabella Chen',
            userAvatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150',
            rating: 5.0,
            comment: 'This PIK villa is absolutely perfect in every way! Stunning architecture with luxury finishes throughout. Living areas are spacious and beautifully designed. Bedrooms are like boutique hotel suites. Bathrooms feature premium fixtures and amenities. Kitchen has professional appliances. Pool and outdoor areas are breathtaking - perfect for entertaining. PIK location offers best of everything - beaches, golf, international dining. Security excellent with 24-hour guard. Villa staff provided impeccable service. Host was amazing. Perfect for luxury family vacation or special celebrations. Cannot recommend highly enough!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-06-22').toISOString(),
            updatedAt: new Date('2024-06-22').toISOString(),
        },

        // Property 87: Modern Loft in Kebayoran Baru, Jakarta - 5 reviews
        {
            propertyId: 87,
            carId: null,
            userId: null,
            userName: 'Daniel Kim',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.5,
            comment: 'Great modern loft in central Kebayoran Baru location. The loft has cool industrial design with high ceilings and large windows. Open floor plan creates spacious feeling. Bedroom area comfortable with good mattress. Bathroom modern and clean. Kitchen has essential appliances. Living space functional with work area. Location is excellent - walking distance to Blok M area with restaurants, cafes, and shopping. Easy public transport access. Building security good. Host responsive. Perfect for young professionals or creative types.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            propertyId: 87,
            carId: null,
            userId: null,
            userName: 'Laura Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.4,
            comment: 'Nice modern loft with character in Kebayoran Baru. Space has urban contemporary vibe with exposed elements. Living area is open and bright with good natural light. Bedroom comfortable enough for good sleep. Bathroom functional with modern fixtures. Kitchen compact but has necessary equipment. Location is convenient - close to Blok M plaza and traditional markets. Good local food options nearby. Building has elevator and parking. WiFi reliable. Host provided helpful local tips. Good value for central South Jakarta location.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            propertyId: 87,
            carId: null,
            userId: null,
            userName: 'Andi Prasetyo',
            userAvatar: null,
            rating: 4.3,
            comment: 'Loft yang menarik dengan style modern industrial di Kebayoran Baru. Design unik dengan ceiling tinggi dan window besar. Layout open plan yang spacious. Bedroom area cukup comfortable. Bathroom clean dengan fixtures modern. Kitchen basic tapi functional. Living space cocok untuk work atau relax. Lokasi strategis dekat dengan Blok M dan public transport. Area sekitar banyak pilihan makan dan shopping. Building cukup secure. Host responsive. Good option untuk solo traveler atau couple yang suka urban living style.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.7,
            value: 4.4,
            createdAt: new Date('2024-04-18').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        {
            propertyId: 87,
            carId: null,
            userId: null,
            userName: 'Michelle Taylor',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            rating: 4.5,
            comment: 'Enjoyed staying in this modern loft in Kebayoran Baru. Space has cool contemporary design with industrial touches. Open layout makes it feel larger than it is. Bedroom area comfortable with decent bed. Bathroom clean and well-maintained. Kitchen has basics for simple cooking. Living area bright with comfortable furniture. Location is great - near shopping, dining, and entertainment. Easy access to TransJakarta and MRT. Building facilities adequate. Host communication good. Good choice for experiencing local Jakarta neighborhood with modern comfort.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-05-25').toISOString(),
            updatedAt: new Date('2024-05-25').toISOString(),
        },
        {
            propertyId: 87,
            carId: null,
            userId: null,
            userName: 'Ryan Murphy',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.4,
            comment: 'Solid modern loft in central Kebayoran Baru area. Loft has contemporary urban design with good use of space. High ceilings create nice atmosphere. Bedroom comfortable for sleeping. Bathroom modern with good shower. Kitchen equipped for basic meals. Living space functional with workspace. Location convenient for exploring Jakarta - near Blok M hub with transport connections. Neighborhood has authentic local character. Building secure with parking available. WiFi speed adequate. Host helpful. Fair price for location and style. Recommended for travelers wanting local experience.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-06-20').toISOString(),
            updatedAt: new Date('2024-06-20').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder for Jakarta properties completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});