import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // Property 101: Executive Penthouse in Tunjungan Plaza Area, Surabaya - 9 reviews
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Alexandra Chen',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
            rating: 5.0,
            comment: 'Absolutely stunning penthouse with breathtaking city views! The location near Tunjungan Plaza is unbeatable - walking distance to premier shopping and dining. The rooftop terrace was perfect for evening drinks while watching the sunset over Surabaya. Interior design is impeccable with high-end furnishings and smart home features. Host was incredibly responsive and provided excellent recommendations for local restaurants. The House of Sampoerna museum nearby was fascinating. This property exceeded all expectations for a luxury stay.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Marcus Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
            rating: 4.9,
            comment: 'Perfect executive accommodation for my business trip. The penthouse office setup with high-speed internet made remote work seamless. Tunjungan Plaza shopping center downstairs is incredibly convenient. The property manager arranged airport pickup and provided insider tips on Surabaya business district. Enjoyed exploring the local food scene in nearby Darmo area. The panoramic windows offer spectacular night views of the city skyline. Only minor issue was occasional elevator wait times during peak hours.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-09-03').toISOString(),
            updatedAt: new Date('2024-09-03').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Sofia Rodriguez',
            userAvatar: null,
            rating: 4.8,
            comment: 'Luxurious stay in the heart of Surabaya! The penthouse amenities are top-notch including the private jacuzzi and wine cellar. Location is prime for shopping enthusiasts - Tunjungan Plaza has everything from international brands to local boutiques. The concierge service was exceptional, helping us book excellent seafood restaurants. Explored the nearby colonial architecture in Gubeng which added cultural dimension to our visit. The property truly delivers a five-star hotel experience with the comfort of a private residence.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'James Liu',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
            rating: 5.0,
            comment: 'Outstanding property that combines luxury with authentic Surabaya living. The chef kitchen was perfect for preparing meals with fresh ingredients from local markets. Tunjungan Plaza location means you are steps away from premium dining and entertainment. Host provided detailed guidebook about Surabaya hidden gems. We particularly enjoyed the rooftop infinity pool at sunset. The smart home automation and premium bedding ensured comfortable stay. Will definitely return on next business trip to East Java.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-10-05').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Emma Andersson',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
            rating: 4.7,
            comment: 'Impressive penthouse with modern aesthetics and premium location. The floor-to-ceiling windows provide amazing natural light throughout the day. Being right at Tunjungan Plaza made shopping and dining incredibly convenient. The property manager was helpful arranging day trips to nearby attractions. We enjoyed exploring Surabaya food scene including famous rawon and rujak cingur. The home theater system was great for relaxing evenings. Only suggestion would be additional parking spaces for guests with vehicles.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 5.0,
            value: 4.5,
            createdAt: new Date('2024-10-22').toISOString(),
            updatedAt: new Date('2024-10-22').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'David Park',
            userAvatar: null,
            rating: 4.9,
            comment: 'Exceptional luxury accommodation in prime Surabaya location. The penthouse design is contemporary yet warm with carefully curated art pieces. Tunjungan Plaza accessibility is unmatched for shopping and dining needs. Host communication was prompt and professional throughout. We explored the House of Sampoerna and colonial heritage sites nearby. The building security and facilities are top-tier. The master suite with ensuite bathroom rivals five-star hotels. Highly recommend for both business travelers and leisure guests.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.7,
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Isabella Santos',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
            rating: 5.0,
            comment: 'Perfect blend of luxury and convenience in downtown Surabaya. The penthouse layout is spacious and thoughtfully designed for entertaining guests. Located right at Tunjungan Plaza means endless shopping and dining options steps away. The host provided excellent recommendations for authentic Surabaya cuisine. We particularly loved the evening ambiance with city lights. The high-end appliances and furnishings show attention to detail. This property sets new standard for premium stays in East Java.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Michael Wagner',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
            rating: 4.8,
            comment: 'Magnificent penthouse that delivers luxury living experience. The smart home features and premium audiovisual systems are impressive. Tunjungan Plaza location provides unparalleled convenience for urban lifestyle. Host was accommodating with early check-in request. We enjoyed exploring nearby Darmo business district and sampling local street food. The rooftop amenities including BBQ area were fantastic for hosting friends. The only improvement would be soundproofing as occasional street noise was noticeable during busy hours.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            propertyId: 101,
            carId: null,
            userId: null,
            userName: 'Yuki Tanaka',
            userAvatar: null,
            rating: 4.9,
            comment: 'Outstanding executive accommodation with world-class amenities. The penthouse office space with dual monitors and ergonomic furniture made working remotely productive. Being at Tunjungan Plaza means access to international restaurants and cafes. The property manager was helpful coordinating cleaning services. We explored Surabaya rich history visiting House of Sampoerna and colonial buildings in Gubeng area. The master bedroom suite with luxury linens ensured restful nights. This property is perfect for extended business stays requiring both work functionality and comfort.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-12-28').toISOString(),
            updatedAt: new Date('2024-12-28').toISOString(),
        },

        // Property 102: Business Hotel Suite in Darmo, Surabaya - 7 reviews
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Robert Martinez',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
            rating: 4.5,
            comment: 'Excellent hotel suite in Darmo business district. The location is perfect for corporate travelers with easy access to major offices and conference centers. Room amenities are comprehensive including workspace with ergonomic chair and high-speed wifi. Staff were professional and accommodating with late checkout request. Enjoyed the proximity to local restaurants serving authentic Surabaya cuisine. The business center facilities met all my printing and meeting needs. Minor issue with air conditioning response time but quickly resolved.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.7,
            location: 4.8,
            value: 4.4,
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Linda Zhang',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
            rating: 4.3,
            comment: 'Solid business accommodation in strategic Darmo location. The suite layout is practical with separate living and sleeping areas. Good selection of local eateries within walking distance. Hotel staff provided helpful maps and directions to Tunjungan Plaza shopping area. The breakfast buffet offered decent variety of Indonesian and Western options. Workspace was functional though could benefit from better lighting. Overall good value for business trips to Surabaya with reliable service and convenient location.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.5,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-09-12').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Thomas Müller',
            userAvatar: null,
            rating: 4.6,
            comment: 'Great mid-range option in Surabaya business hub. The suite is spacious and well-maintained with modern furnishings. Darmo area offers good mix of business facilities and dining options. Hotel concierge was helpful arranging transportation to meetings across the city. We explored nearby Pakuwon City on weekend which was interesting. The meeting room rental rates were reasonable for client presentations. Wifi connection was stable throughout stay. Would recommend for business travelers seeking value and convenience.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.7,
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-01').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Maria Garcia',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
            rating: 4.4,
            comment: 'Comfortable business suite with practical amenities. Located in active Darmo district with easy access to corporate offices and restaurants. The kitchenette was useful for preparing light meals. Staff were courteous and responsive to requests. We enjoyed trying local Surabaya specialties at nearby warungs. The workspace setup with large desk and proper lighting was adequate for remote work. Building security was reassuring. Some wear on furniture but overall clean and functional accommodation.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.6,
            value: 4.6,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-10-28').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Andrew Kim',
            userAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
            rating: 4.2,
            comment: 'Decent hotel suite for business purposes in Darmo area. The location provides good access to Surabaya business centers. Room was clean with functional workspace and reliable internet. Hotel staff were helpful with local information and taxi arrangements. Explored House of Sampoerna museum during free time which was worthwhile. The breakfast service was adequate though limited variety. Room soundproofing could be improved as street noise was noticeable. Fair value for money considering location and facilities offered.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.4,
            location: 4.5,
            value: 4.4,
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Rachel Foster',
            userAvatar: null,
            rating: 4.7,
            comment: 'Well-appointed business suite in convenient Darmo location. The property met expectations with clean rooms and responsive management. Good proximity to business district made daily commute efficient. We appreciated the flexibility with checkout times. The suite common areas were well-maintained. Enjoyed sampling Surabaya food scene with excellent rawon and sate recommendations from staff. The workspace ergonomics were better than typical hotel rooms. Reliable choice for corporate travelers needing comfortable base in Surabaya.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            propertyId: 102,
            carId: null,
            userId: null,
            userName: 'Daniel Petersen',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
            rating: 4.5,
            comment: 'Practical accommodation in Surabaya business hub. The suite design balances work and relaxation needs effectively. Darmo location is strategic for accessing major corporate offices. Hotel team was professional handling housekeeping and maintenance requests. We took weekend trip to explore Gubeng colonial architecture which added cultural element. The business lounge was quiet and suitable for client calls. Room amenities met business traveler needs. Good alternative to international hotel chains with more personal service and local character.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },

        // Property 103: Modern Apartment in Pakuwon City, Surabaya - 6 reviews
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Jennifer Brown',
            userAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400',
            rating: 4.4,
            comment: 'Nice modern apartment in Pakuwon City integrated township. The location offers complete urban living with mall, supermarket and restaurants all connected. Apartment is well-furnished with contemporary design and functional layout. We enjoyed the convenience of having everything within the complex. The swimming pool and gym facilities were good additions. Host provided clear instructions for access and parking. Explored nearby Darmo area and Tunjungan Plaza easily. Minor issues with hot water consistency but overall pleasant stay.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-08-28').toISOString(),
            updatedAt: new Date('2024-08-28').toISOString(),
        },
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Kevin O\'Connor',
            userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
            rating: 4.3,
            comment: 'Comfortable apartment in well-planned Pakuwon City development. The integrated township concept is impressive with complete facilities. Apartment has modern amenities and decent space for small family. Building security and maintenance were reliable. We appreciated the onsite supermarket for groceries. The location provides easy access to Surabaya business districts. Tried various restaurants in the complex offering diverse cuisines. Wifi speed was good for remote work. Would prefer slightly larger balcony but overall solid urban accommodation.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.5,
            value: 4.4,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Sarah Johnson',
            userAvatar: null,
            rating: 4.6,
            comment: 'Great apartment in thriving Pakuwon City area. The modern design and smart layout make efficient use of space. Loved the convenience of shopping mall and cinema in same complex. Host was responsive and provided helpful local tips. We explored Surabaya attractions including House of Sampoerna and colonial sites. The apartment amenities like washer and full kitchen were very practical. Building facilities including pool and gym added value. Good choice for families or extended business stays wanting urban convenience.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-10-18').toISOString(),
            updatedAt: new Date('2024-10-18').toISOString(),
        },
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Marco Rossi',
            userAvatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400',
            rating: 4.2,
            comment: 'Decent modern apartment in Pakuwon City township. The location benefits from integrated facilities making daily life convenient. Apartment is clean with functional furnishings. We enjoyed the variety of dining options within walking distance. Building management was helpful with parking and deliveries. The township development is interesting example of urban planning. Wifi connection was reliable for work needs. Some kitchen equipment could be upgraded but adequate for basic cooking. Fair value for comfortable Surabaya accommodation.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.3,
            location: 4.4,
            value: 4.3,
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Nicole Adams',
            userAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400',
            rating: 4.5,
            comment: 'Pleasant stay in well-located Pakuwon City apartment. The integrated township offers excellent convenience with shopping, dining and entertainment options. Apartment has contemporary design with good natural lighting. Host communication was clear and timely. We appreciated the security and cleanliness of the building. Explored Tunjungan Plaza and local food scene during our visit. The living room setup was comfortable for relaxing evenings. Minor maintenance items noted but management responsive. Recommended for travelers wanting modern urban living experience.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.5,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            propertyId: 103,
            carId: null,
            userId: null,
            userName: 'Patrick Murphy',
            userAvatar: null,
            rating: 4.4,
            comment: 'Good apartment in strategic Pakuwon City location. The township concept provides complete living infrastructure. Apartment is modern with practical layout for small families. We enjoyed the onsite facilities including pool and fitness center. Building security gave peace of mind. The proximity to business districts made commuting efficient. Sampled various restaurants in the complex with good variety. Host provided useful information about Surabaya attractions. Hot water could be more consistent. Overall reliable choice for medium-term stays in Surabaya.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.4,
            location: 4.6,
            value: 4.4,
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },

        // Property 104: Colonial Style House in Gubeng, Surabaya - 8 reviews
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Catherine Laurent',
            userAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400',
            rating: 4.8,
            comment: 'Charming colonial house in historic Gubeng neighborhood. The property beautifully preserves original architecture while offering modern comforts. Loved the high ceilings, wooden details and vintage furniture that create authentic atmosphere. Located in quiet residential area yet close to Tunjungan Plaza and Darmo business district. Host shared fascinating stories about house history and Surabaya colonial heritage. We visited nearby House of Sampoerna and explored architectural gems. The garden courtyard was perfect for morning coffee. Exceptional experience blending history and comfort.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.7,
            value: 4.7,
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'William Turner',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
            rating: 4.9,
            comment: 'Outstanding colonial property in Gubeng historical district. The house restoration maintains authentic character with period furniture and vintage decor. High ceilings and original tile work are remarkable. Garden with tropical plants creates serene escape in urban setting. Host was knowledgeable about Surabaya history providing excellent cultural context. We explored surrounding colonial architecture and sampled local cuisine at nearby warungs. The house offers unique alternative to generic hotels with real heritage value. Perfect for history enthusiasts and architecture lovers.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.8,
            value: 4.8,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Olivia Bennett',
            userAvatar: null,
            rating: 4.7,
            comment: 'Beautiful heritage house in charming Gubeng area. The colonial architecture with wooden shutters and antique furnishings transports you back in time. Modern amenities like AC and wifi integrated thoughtfully without compromising character. Neighborhood is peaceful with tree-lined streets and historical buildings. Host provided detailed guidebook about Surabaya colonial sites. We enjoyed exploring House of Sampoerna and local markets. The spacious rooms and vintage bathroom fixtures were delightful. Slight street noise in early morning but charming ambiance compensates.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.6,
            value: 4.6,
            createdAt: new Date('2024-09-22').toISOString(),
            updatedAt: new Date('2024-09-22').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Hans Weber',
            userAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400',
            rating: 4.8,
            comment: 'Magnificent colonial residence in historic Gubeng neighborhood. The property showcases excellent preservation of Dutch East Indies architecture. Original features including terrazzo floors and carved wood details are stunning. Garden courtyard with fountain provides tranquil setting. Host passion for heritage was evident in every detail. We explored surrounding colonial buildings and visited Tunjungan Plaza for shopping. The vintage kitchen still functions perfectly. This house offers cultural immersion rarely found in modern accommodations. Highly recommended for travelers appreciating architectural heritage.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.7,
            value: 4.7,
            createdAt: new Date('2024-10-10').toISOString(),
            updatedAt: new Date('2024-10-10').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Sophie Dubois',
            userAvatar: 'https://images.unsplash.com/photo-1502378735452-bc7d86632805?w=400',
            rating: 4.6,
            comment: 'Lovely colonial house full of character in Gubeng district. The property balances historical authenticity with modern comfort effectively. High ceilings and spacious rooms create airy atmosphere. We appreciated the antique furniture collection and vintage decor. Garden with tropical plants was pleasant retreat. Host shared interesting history about Dutch colonial period in Surabaya. Location allows easy exploration of House of Sampoerna and business districts. Some plumbing could be modernized but adds to authentic experience. Wonderful stay for those seeking cultural connection.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.7,
            location: 4.5,
            value: 4.5,
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-10-30').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Richard Clarke',
            userAvatar: null,
            rating: 4.9,
            comment: 'Exceptional colonial property in authentic Gubeng neighborhood. The house restoration is masterful preserving architectural integrity while ensuring comfort. Original tile work, wooden beams and vintage fixtures are remarkable. Garden courtyard offers peaceful sanctuary. Host was excellent resource for Surabaya history and culture. We explored nearby colonial architecture and sampled local food at traditional restaurants. The period furniture and decor create immersive historical experience. This property stands out as genuine heritage accommodation. Perfect for travelers valuing cultural authenticity and architectural beauty.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.8,
            value: 4.8,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Amelia Harrison',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
            rating: 4.7,
            comment: 'Wonderful heritage house in historic Gubeng area. The colonial architecture with original features creates unique ambiance. High ceilings and vintage shutters provide natural cooling. We loved the antique furniture and historical photographs throughout. Garden was perfect for breakfast surrounded by tropical greenery. Host provided fascinating insights into Surabaya colonial past. Easy access to Tunjungan Plaza and local attractions. The house offers authentic cultural experience beyond typical tourist accommodation. Minor updates needed in bathroom but character compensates. Highly recommended for heritage enthusiasts.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.8,
            location: 4.6,
            value: 4.6,
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            propertyId: 104,
            carId: null,
            userId: null,
            userName: 'Charles Fontaine',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
            rating: 4.8,
            comment: 'Remarkable colonial residence in charming Gubeng district. The property exemplifies Dutch East Indies architecture with period authenticity. Original terrazzo floors, carved woodwork and vintage fixtures are beautifully maintained. Garden courtyard with fountain creates peaceful oasis. Host knowledge of Surabaya history enriched our stay significantly. We explored House of Sampoerna museum and colonial buildings nearby. The house offers rare opportunity to experience historical living. Modern amenities integrated seamlessly without compromising character. Outstanding choice for travelers seeking cultural depth and architectural appreciation.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.7,
            value: 4.7,
            createdAt: new Date('2024-12-26').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },

        // Property 105: Heritage Villa in Kotagede, Yogyakarta - 10 reviews
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Victoria Cambridge',
            userAvatar: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400',
            rating: 5.0,
            comment: 'Absolutely stunning heritage villa in historic Kotagede silver district. The property is masterpiece of Javanese architecture with intricate carved details and traditional joglo structure. Located in heart of silver craft quarter allowing exploration of artisan workshops. Host was exceptional providing cultural insights and arranging batik tours. We visited Kraton palace, Borobudur temple and Prambanan which were breathtaking. The villa garden with traditional pavilion was perfect for evening tea. Every detail reflects authentic Javanese heritage. This property offers unparalleled cultural immersion experience.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Philippe Moreau',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
            rating: 4.9,
            comment: 'Magnificent villa showcasing authentic Javanese heritage in Kotagede. The traditional architecture with carved teakwood and joglo roof is spectacular. Surrounded by silver workshops where we watched artisans at work. Host knowledge of Yogyakarta culture and history was invaluable. We explored Kraton palace complex and took day trips to Borobudur and Prambanan temples. The villa courtyard with tropical garden creates serene atmosphere. Experiencing traditional Javanese breakfast in open pavilion was memorable. Property beautifully preserves cultural heritage while providing modern comfort.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Anastasia Popov',
            userAvatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400',
            rating: 5.0,
            comment: 'Exceptional heritage property in culturally rich Kotagede area. The villa exemplifies traditional Javanese architecture with magnificent carved woodwork and authentic joglo construction. Being in silver craft district allowed unique insights into local craftsmanship. Host arranged wonderful batik making workshop and gamelan music experience. We visited spectacular Borobudur at sunrise and explored Prambanan temples. The traditional garden with fish pond and pavilion was incredibly peaceful. Property offers genuine cultural immersion rarely found in typical accommodations. Absolutely unforgettable Yogyakarta experience.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Jonathan Wright',
            userAvatar: null,
            rating: 4.8,
            comment: 'Outstanding Javanese villa in historic Kotagede district. The traditional architecture with intricate wood carvings demonstrates exceptional craftsmanship. Location in silver artisan quarter provides authentic cultural context. Host was wonderful organizing temple tours and traditional dance performances. We explored Kraton palace, Malioboro street shopping and visited famous Borobudur temple. The villa garden with traditional pendopo was perfect for relaxation. Experiencing Javanese hospitality and culture here was highlight of our Indonesia trip. Minor modernization in bathrooms would enhance comfort but authenticity is priority.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Isabella Romano',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
            rating: 4.9,
            comment: 'Breathtaking heritage villa in culturally significant Kotagede. The traditional Javanese joglo architecture with carved teakwood is masterpiece. Surrounded by silver workshops where we commissioned custom pieces. Host expertise in Yogyakarta culture enriched every day. We visited Borobudur at sunrise, explored Prambanan temples and Kraton palace. The villa courtyard garden with traditional pavilion offers tranquil retreat. Batik workshop arranged by host was fascinating cultural experience. Property perfectly balances heritage preservation with guest comfort. This is authentic Yogyakarta experience at its finest.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-10-08').toISOString(),
            updatedAt: new Date('2024-10-08').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Henrik Larsen',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
            rating: 5.0,
            comment: 'Spectacular Javanese heritage villa in Kotagede silver district. The traditional architecture showcases magnificent wood carving artistry and authentic joglo structure. Location allows immersion in silver crafting tradition with workshops nearby. Host was exceptional guide to Yogyakarta culture arranging temple visits and cultural performances. We explored Borobudur, Prambanan, and Kraton palace which were incredible. The villa garden with koi pond and traditional pendopo creates peaceful sanctuary. Every architectural detail tells story of Javanese heritage. This property offers unmatched cultural experience in Yogyakarta.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-10-28').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Charlotte Dubois',
            userAvatar: null,
            rating: 4.8,
            comment: 'Magnificent traditional villa in historic Kotagede area. The Javanese joglo architecture with intricate carvings is breathtaking. Being in silver craft quarter provided unique cultural insights. Host arranged wonderful batik workshop and gamelan music session. We visited stunning Borobudur and Prambanan temples, explored Kraton palace and shopped at Malioboro. The villa garden with traditional pavilion was incredibly peaceful. Experiencing authentic Javanese hospitality here was unforgettable. Some modern amenities could be upgraded but authenticity is what makes this special. Highly recommended for cultural travelers.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.9,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Sebastian Fischer',
            userAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
            rating: 4.9,
            comment: 'Extraordinary heritage property in culturally rich Kotagede. The traditional Javanese villa with carved woodwork and joglo roof exemplifies architectural mastery. Located in heart of silver artisan district adding authentic dimension. Host knowledge of Yogyakarta history and culture was remarkable. We explored Borobudur temple complex, visited Prambanan and experienced Kraton palace traditions. The villa courtyard garden with fish pond creates serene environment. Traditional Javanese breakfast in open pavilion was delightful. Property offers genuine cultural immersion beyond typical tourist experience.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Eleonora Conti',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
            rating: 5.0,
            comment: 'Absolutely stunning Javanese villa in historic Kotagede district. The traditional joglo architecture with magnificent wood carvings is masterpiece of cultural heritage. Surrounded by silver workshops providing authentic artisan experience. Host was wonderful organizing cultural activities including batik making and traditional dance. We visited breathtaking Borobudur and Prambanan temples, explored Kraton palace complex. The villa garden with traditional pavilion and koi pond offers peaceful retreat. Every detail reflects deep respect for Javanese traditions. This property delivers unparalleled cultural immersion in Yogyakarta.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            propertyId: 105,
            carId: null,
            userId: null,
            userName: 'Alexander Novak',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
            rating: 4.9,
            comment: 'Remarkable heritage villa showcasing authentic Javanese architecture in Kotagede. The traditional joglo structure with intricate carved teakwood is spectacular. Location in silver craft district allows exploration of local artisan traditions. Host passion for culture was evident arranging temple tours and gamelan performances. We explored magnificent Borobudur, visited Prambanan temples and Kraton palace. The villa courtyard garden with traditional pendopo creates tranquil sanctuary. Experiencing genuine Javanese hospitality and cultural immersion here was exceptional. This property offers rare opportunity to connect with living cultural heritage.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-12-30').toISOString(),
            updatedAt: new Date('2024-12-30').toISOString(),
        },

        // Property 106: Boutique Hotel in Prawirotaman, Yogyakarta - 8 reviews
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Emily Richardson',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
            rating: 4.5,
            comment: 'Charming boutique hotel in vibrant Prawirotaman backpacker district. The property combines traditional Javanese design elements with modern comfort. Located on lively street with cafes, restaurants and art galleries. Staff were friendly helping arrange temple tours to Borobudur and Prambanan. We enjoyed exploring Malioboro street shopping and visited Kraton palace. The hotel courtyard garden was pleasant retreat from busy streets. Breakfast included local and Western options. Good base for exploring Yogyakarta cultural attractions. Minor noise from street in evenings but location benefits outweigh this.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Lucas Schmidt',
            userAvatar: null,
            rating: 4.4,
            comment: 'Nice boutique accommodation in lively Prawirotaman area. The hotel design incorporates Javanese touches while maintaining functionality. Surrounded by traveler-friendly cafes and restaurants serving diverse cuisines. Hotel staff were helpful booking day trips to Borobudur temple. We explored university town atmosphere and visited local batik workshops. The common areas encourage socializing with other guests. Rooms are clean though compact. Good wifi for staying connected. Location is perfect for experiencing Yogyakarta backpacker culture while having comfortable accommodation.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-08').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Maya Patel',
            userAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400',
            rating: 4.6,
            comment: 'Lovely boutique hotel in energetic Prawirotaman district. The property balances traditional aesthetics with modern amenities well. Excellent location for exploring Yogyakarta with easy access to Malioboro and temples. Staff arranged convenient transportation to Borobudur sunrise tour. We enjoyed the vibrant street life with art galleries and live music venues. Hotel garden courtyard provides peaceful escape. Breakfast variety was good with Indonesian specialties. The hotel captures essence of Yogyakarta backpacker scene while offering comfort. Great value for cultural exploration base.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.7,
            createdAt: new Date('2024-10-02').toISOString(),
            updatedAt: new Date('2024-10-02').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Oliver Hansen',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
            rating: 4.3,
            comment: 'Comfortable boutique hotel in popular Prawirotaman area. The property offers good mix of traditional design and practical facilities. Located in heart of backpacker district with numerous dining and entertainment options. Hotel team was accommodating helping plan temple visits to Prambanan. We explored Yogyakarta university culture and attended traditional dance performance. The rooftop area was nice for evening relaxation. Rooms meet basic needs though bathrooms could use updating. Fair pricing for location and service. Good choice for budget-conscious travelers wanting cultural experience.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.5,
            value: 4.5,
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Sophia Martinez',
            userAvatar: null,
            rating: 4.7,
            comment: 'Delightful boutique property in vibrant Prawirotaman neighborhood. The hotel successfully combines Javanese architectural elements with contemporary comfort. Surrounded by eclectic mix of cafes, galleries and shops. Staff were excellent organizing Borobudur temple tour and batik workshop. We enjoyed exploring Malioboro street and Kraton palace complex. The hotel garden with traditional pavilion was lovely spot for breakfast. Social atmosphere makes it easy meeting fellow travelers. Rooms are well-maintained and clean. Highly recommend for travelers seeking cultural immersion in Yogyakarta.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.7,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Nathan Cooper',
            userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
            rating: 4.5,
            comment: 'Great boutique hotel in lively Prawirotaman backpacker hub. The property design incorporates traditional Javanese touches throughout. Perfect location for accessing Yogyakarta cultural sites and nightlife. Hotel arranged convenient Prambanan temple visit and silver workshop tour. We explored university atmosphere and sampled diverse local cuisine. The common lounge area encourages guest interaction. Staff were friendly and knowledgeable about area attractions. Rooms are functional though air conditioning could be stronger. Excellent value offering authentic Yogyakarta experience.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Zara Ahmed',
            userAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400',
            rating: 4.4,
            comment: 'Pleasant boutique accommodation in energetic Prawirotaman district. The hotel offers comfortable rooms with traditional decorative elements. Located in heart of backpacker area with easy access to restaurants and entertainment. Staff helped coordinate Borobudur sunrise tour which was spectacular. We enjoyed exploring Malioboro market and Kraton palace. The hotel garden provides quiet space away from street activity. Breakfast included good selection of local dishes. Some maintenance items noted but overall clean and functional. Good budget option for Yogyakarta cultural exploration.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.5,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            propertyId: 106,
            carId: null,
            userId: null,
            userName: 'Ethan Brooks',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
            rating: 4.6,
            comment: 'Solid boutique hotel in vibrant Prawirotaman neighborhood. The property successfully blends traditional Javanese design with modern necessities. Excellent location for experiencing Yogyakarta backpacker culture and accessing major attractions. Hotel team was helpful arranging temple tours to Borobudur and Prambanan. We explored university town atmosphere and attended traditional gamelan performance. The rooftop terrace was great for evening socializing. Rooms are well-maintained with comfortable beds. Good wifi throughout property. Recommended for travelers wanting authentic Yogyakarta experience with comfortable base.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-12-28').toISOString(),
            updatedAt: new Date('2024-12-28').toISOString(),
        },

        // Property 107: Contemporary Apartment in Sleman, Yogyakarta - 6 reviews
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Grace Wilson',
            userAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400',
            rating: 4.3,
            comment: 'Modern apartment in Sleman university district. The property offers contemporary design with practical layout for extended stays. Located in student area with affordable dining options and cafes. Host provided clear instructions and was responsive. We explored nearby university campuses and visited Borobudur temple. The apartment has good amenities including kitchen and washing machine. Area is quieter compared to downtown Yogyakarta. Good local transportation connections to Malioboro and Kraton palace. Some furniture showing wear but overall clean and functional accommodation.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.2,
            value: 4.4,
            createdAt: new Date('2024-08-30').toISOString(),
            updatedAt: new Date('2024-08-30').toISOString(),
        },
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Ryan Mitchell',
            userAvatar: null,
            rating: 4.2,
            comment: 'Decent contemporary apartment in Sleman area. The property is functional with modern amenities. Surrounded by university atmosphere with student-friendly restaurants and affordable eateries. Apartment has basic necessities including wifi and air conditioning. Host was helpful with local recommendations. We took day trips to Prambanan temple and explored Malioboro market. The location is more residential offering quiet environment. Transportation to main attractions requires motorcycle or car. Suitable for travelers preferring local neighborhood experience over tourist center.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.3,
            location: 4.1,
            value: 4.3,
            createdAt: new Date('2024-09-28').toISOString(),
            updatedAt: new Date('2024-09-28').toISOString(),
        },
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Mia Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1502378735452-bc7d86632805?w=400',
            rating: 4.4,
            comment: 'Good modern apartment in Sleman university district. The property offers contemporary living space with practical amenities. Located in active student area with diverse food options. We appreciated the full kitchen for preparing meals. Host communication was clear and timely. Explored Yogyakarta from this base visiting Borobudur, Prambanan and Kraton palace. The area provides authentic local living experience away from tourist crowds. Good wifi for remote work needs. Transportation apps work well for getting around city. Fair value for comfortable Yogyakarta accommodation.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.4,
            location: 4.3,
            value: 4.5,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Leo Andersson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
            rating: 4.1,
            comment: 'Functional contemporary apartment in Sleman neighborhood. The property meets basic needs with modern facilities. Surrounded by university culture with affordable local restaurants. Apartment is clean with essential amenities. Host provided useful information about area. We visited Borobudur temple and explored batik workshops. The location offers quiet residential setting. Distance from main tourist areas requires transportation planning. Kitchen equipment adequate for basic cooking. Internet connection was reliable. Suitable for budget travelers wanting local neighborhood experience in Yogyakarta.',
            cleanliness: 4.2,
            accuracy: 4.1,
            communication: 4.2,
            location: 4.0,
            value: 4.2,
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Chloe Davis',
            userAvatar: null,
            rating: 4.5,
            comment: 'Nice modern apartment in Sleman university area. The property offers contemporary design with good natural lighting. Located in vibrant student district with variety of affordable dining options. Apartment has practical layout with full kitchen and washing facilities. Host was responsive answering questions promptly. We explored Yogyakarta cultural sites from this base. The area provides authentic local living experience. Good public transportation access to Malioboro and temples. Some updating needed in bathroom fixtures. Overall solid value for comfortable stay in residential Yogyakarta neighborhood.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.5,
            location: 4.4,
            value: 4.5,
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            propertyId: 107,
            carId: null,
            userId: null,
            userName: 'Isaac Roberts',
            userAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
            rating: 4.3,
            comment: 'Practical contemporary apartment in Sleman district. The property provides modern living space with essential amenities. Surrounded by university atmosphere offering authentic local experience. Apartment is well-maintained with functional kitchen. Host provided helpful local information and recommendations. We visited Prambanan temple and explored Kraton palace complex. The location is quieter than downtown tourist areas. Transportation to main attractions easily arranged through ride-sharing apps. Wifi speed was adequate for work needs. Fair pricing for comfortable accommodation in residential Yogyakarta area.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.4,
            location: 4.2,
            value: 4.4,
            createdAt: new Date('2024-12-25').toISOString(),
            updatedAt: new Date('2024-12-25').toISOString(),
        }
    ];

    await db.insert(reviews).values(sampleReviews);

    console.log('✅ Reviews seeder completed successfully - 54 reviews added for Surabaya and Yogyakarta properties');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});