import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // Property 88: Colonial Heritage Villa - 10 reviews (4.6-5.0 ratings)
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Sophie Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
            rating: 5.0,
            comment: 'The Colonial Heritage Villa in Dago exceeded all expectations! The architecture is absolutely stunning with its classic Dutch colonial design. Bandung\'s cool mountain climate made our stay incredibly comfortable. The villa\'s location in Dago is perfect - quiet yet close to everything. We enjoyed morning walks around the historic neighborhood and the views of the surrounding hills are breathtaking. The attention to detail in preserving the colonial character while providing modern amenities was impressive.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Marcus Chen',
            userAvatar: null,
            rating: 4.9,
            comment: 'Staying at this villa was like stepping back in time. The colonial architecture is beautifully maintained and the spacious rooms are filled with character. Dago area is one of Bandung\'s most prestigious neighborhoods and it shows. We loved the cool weather - such a relief from Jakarta\'s heat! The villa\'s garden is magnificent and perfect for evening relaxation. Staff was incredibly helpful with restaurant recommendations and arranging tours around Bandung. Worth every rupiah for a luxury heritage experience.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.6,
            createdAt: new Date('2024-08-02').toISOString(),
            updatedAt: new Date('2024-08-02').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Isabella Rodriguez',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
            rating: 4.8,
            comment: 'What a magnificent property! The colonial villa captures the essence of Bandung\'s rich history. High ceilings, antique furniture, and beautiful wooden details throughout. The location in Dago is superb - we walked to nearby cafes and enjoyed the tree-lined streets. Bandung\'s pleasant climate made outdoor activities enjoyable. The villa provides a peaceful retreat while being close to the city center. Photography enthusiasts will love the architectural details and surrounding landscapes.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-08-18').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'James Patterson',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
            rating: 5.0,
            comment: 'Absolutely exceptional heritage property! The villa\'s colonial charm is perfectly preserved with modern comforts seamlessly integrated. Dago neighborhood offers wonderful dining options and the cool mountain air of Bandung is refreshing. We spent evenings on the veranda enjoying the views and peaceful atmosphere. The host provided excellent local insights and the property manager was always available. This villa offers a unique glimpse into Bandung\'s colonial past while providing five-star comfort.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Yuki Tanaka',
            userAvatar: null,
            rating: 4.7,
            comment: 'Wonderful colonial villa experience in Dago! The architecture and interior design transport you to another era. Bandung\'s cool climate was perfect for our visit - much more comfortable than tropical heat. The villa\'s location offers easy access to Bandung\'s attractions while maintaining privacy and tranquility. Spacious rooms, beautiful gardens, and thoughtful amenities made our stay memorable. Great for families or groups wanting a luxurious heritage experience.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.6,
            location: 4.8,
            value: 4.5,
            createdAt: new Date('2024-09-22').toISOString(),
            updatedAt: new Date('2024-09-22').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Emma Thompson',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
            rating: 4.9,
            comment: 'The Colonial Heritage Villa is a true gem in Bandung! From the moment we arrived, we were impressed by the authentic colonial architecture and elegant interiors. The Dago area is sophisticated and peaceful, perfect for a relaxing getaway. Bandung\'s mountain climate kept everything fresh and pleasant. The villa\'s amenities are top-notch and the staff went above and beyond. We explored nearby historical sites and enjoyed wonderful local cuisine. Highly recommend for anyone seeking luxury and history combined.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.9,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-10-08').toISOString(),
            updatedAt: new Date('2024-10-08').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Lucas van der Berg',
            userAvatar: null,
            rating: 4.6,
            comment: 'Beautiful heritage villa with authentic Dutch colonial character. The location in Dago is prestigious and convenient. Bandung\'s cooler weather made our stay very comfortable. The villa is spacious with high ceilings and period furniture that adds to the ambiance. Garden area is lovely for morning coffee. Staff was professional and accommodating. Minor issues with WiFi stability but overall a fantastic experience for history enthusiasts and luxury travelers.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.4,
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Priya Sharma',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
            rating: 5.0,
            comment: 'Outstanding colonial villa experience! The property perfectly captures Bandung\'s colonial heritage with its architecture and design. Dago area is charming with tree-lined streets and excellent dining options nearby. The cool mountain climate of Bandung was wonderful - we didn\'t need air conditioning at all! Every room in the villa is beautifully appointed with antiques and modern comforts. The host provided detailed information about Bandung\'s history and attractions. Perfect for a memorable luxury stay.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-11-10').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Alexandre Dubois',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
            rating: 4.8,
            comment: 'Magnificent colonial property in the heart of Dago! The villa maintains its historical character beautifully while offering all modern conveniences. Bandung\'s pleasant climate and mountain views create a perfect setting. We appreciated the spacious layout and elegant furnishings throughout. The location provides easy access to Bandung\'s attractions while offering a peaceful retreat. Staff communication was excellent and they helped arrange transportation. Ideal for experiencing Bandung\'s colonial heritage in style.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.8,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            propertyId: 88,
            carId: null,
            userId: null,
            userName: 'Sarah Mitchell',
            userAvatar: null,
            rating: 4.9,
            comment: 'Exceptional stay at this colonial villa! The architecture is stunning and the attention to detail in restoration is impressive. Dago neighborhood is one of Bandung\'s finest areas with great restaurants and cafes nearby. The cool weather made our stay incredibly comfortable - perfect escape from tropical heat. Villa grounds are beautifully maintained and the interior design combines historical charm with luxury amenities. Staff was helpful with local recommendations. Highly recommend for anyone visiting Bandung!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.8,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },

        // Property 89: Mountain View Apartment in Lembang - 6 reviews (4.0-4.7 ratings)
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'David Kim',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
            rating: 4.5,
            comment: 'Great apartment in Lembang with stunning mountain views! The location is perfect for exploring Bandung\'s highlands and the cool climate is refreshing. We enjoyed visiting nearby Tangkuban Perahu volcano and Farmhouse Lembang. The apartment is clean and well-equipped with everything needed for a comfortable stay. Host was responsive and provided good local tips. Parking available and easy access to Lembang\'s attractions. Good value for money especially for families wanting mountain getaway.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.4,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'Maria Santos',
            userAvatar: null,
            rating: 4.3,
            comment: 'Nice mountain apartment in Lembang area. The views are beautiful and we loved the cool mountain air. Close to many Lembang attractions like floating market and tea plantations. Apartment is basic but functional with comfortable beds and hot water. Kitchen facilities were helpful for preparing simple meals. WiFi worked well. Would recommend bringing warm clothes as nights get quite cool. Good base for exploring Bandung highlands at reasonable price.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.2,
            location: 4.5,
            value: 4.5,
            createdAt: new Date('2024-09-14').toISOString(),
            updatedAt: new Date('2024-09-14').toISOString(),
        },
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'Thomas Weber',
            userAvatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop',
            rating: 4.6,
            comment: 'Excellent mountain retreat in Lembang! The apartment offers fantastic views of Bandung\'s surrounding hills and volcanoes. We spent our days visiting nearby strawberry farms and hot springs. The cool climate was perfect - needed a jacket in the evenings which was lovely. Apartment is well-maintained and has all essential amenities. Location is convenient for Lembang attractions yet peaceful. Host provided clear directions and check-in was smooth. Great value for experiencing Bandung\'s mountain region.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-10-02').toISOString(),
            updatedAt: new Date('2024-10-02').toISOString(),
        },
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'Aisha Rahman',
            userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop',
            rating: 4.2,
            comment: 'Decent apartment for Lembang stay. Mountain views from balcony are lovely and the fresh air is wonderful. Close to Lembang\'s tourist spots which made day trips easy. Apartment is clean with basic furnishings and working appliances. Water pressure could be better and some furniture shows wear. However, for the price and location, it\'s good value. Host was friendly and helpful with directions. Recommended for budget-conscious travelers wanting to explore Bandung highlands.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.1,
            location: 4.4,
            value: 4.4,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'Marco Rossi',
            userAvatar: null,
            rating: 4.7,
            comment: 'Very pleasant stay in Lembang! The apartment provides beautiful mountain scenery and cool weather that Bandung highlands are famous for. We enjoyed exploring nearby Lembang attractions including waterfalls and farms. Apartment is cozy and comfortable with good heating for chilly nights. Kitchen is equipped for cooking and supermarket nearby. Host communicated well and responded quickly to questions. Parking is convenient. Great location for nature lovers and families. Will definitely return!',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.6,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            propertyId: 89,
            carId: null,
            userId: null,
            userName: 'Jennifer Lee',
            userAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop',
            rating: 4.4,
            comment: 'Good mountain apartment experience in Lembang. The views are spectacular especially during sunrise. Cool climate of Bandung highlands is refreshing and perfect for outdoor activities. We visited Tangkuban Perahu volcano and several tea plantations nearby. Apartment has essential amenities and is clean. WiFi works well for remote work. Some minor maintenance needed but overall comfortable. Host was accommodating with late check-in. Fair pricing for location and mountain views.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.6,
            value: 4.5,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },

        // Property 90: Boutique Hotel Room in Riau, Bandung - 7 reviews (4.0-4.7 ratings)
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Oliver Johnson',
            userAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop',
            rating: 4.5,
            comment: 'Excellent boutique hotel in the heart of Riau! The location is unbeatable - right in Bandung\'s shopping district with countless stores, restaurants, and cafes within walking distance. Room is stylishly decorated with modern amenities and comfortable bed. Staff is friendly and helpful with recommendations. Bandung\'s cool climate makes city exploring pleasant. We loved being able to walk to Riau street shops and try local street food. Great value for central location and quality accommodation.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.5,
            location: 4.9,
            value: 4.6,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-07-25').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Nina Patel',
            userAvatar: null,
            rating: 4.3,
            comment: 'Nice boutique room in Riau area. Perfect location for shopping enthusiasts - Riau street has amazing factory outlets and local shops. Room is compact but well-designed with everything needed. Hotel staff was professional and breakfast included was decent. The cool weather in Bandung made walking around comfortable. Some street noise at night but manageable. Good WiFi and hot shower. Ideal for short stays focused on shopping and dining in central Bandung.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.2,
            location: 4.7,
            value: 4.4,
            createdAt: new Date('2024-08-28').toISOString(),
            updatedAt: new Date('2024-08-28').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Carlos Mendez',
            userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
            rating: 4.6,
            comment: 'Great boutique hotel experience on Riau street! The room is beautifully designed with attention to detail and modern comforts. Location is fantastic - surrounded by Bandung\'s best shopping and dining options. We enjoyed exploring nearby cafes and trying local cuisine. Staff went above and beyond with service. Bandung\'s pleasant climate and the hotel\'s central location made our stay enjoyable. Room was clean and quiet despite busy location. Highly recommend for city explorers!',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Stephanie Wong',
            userAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop',
            rating: 4.2,
            comment: 'Solid boutique hotel in Riau district. Room is small but efficiently designed with good storage. The location on Riau street is excellent for shopping - we found great deals at factory outlets nearby. Bandung\'s cool weather made walking around pleasant. Hotel amenities are basic but functional. Staff was helpful with directions and restaurant suggestions. Some noise from street but not too disruptive. Fair price for central Bandung location. Good for budget-conscious travelers.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.1,
            location: 4.6,
            value: 4.3,
            createdAt: new Date('2024-10-12').toISOString(),
            updatedAt: new Date('2024-10-12').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Henrik Larsson',
            userAvatar: null,
            rating: 4.7,
            comment: 'Wonderful boutique hotel right on Riau! The room exceeded expectations with stylish decor and comfortable furnishings. Being in the heart of Bandung\'s shopping district was perfect - we could walk to countless stores and restaurants. The cool mountain climate of Bandung made city exploration enjoyable. Hotel staff was exceptional with local knowledge and service. Breakfast was good quality. WiFi strong and reliable. Excellent value for location and amenities. Will stay again!',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.7,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Rachel Green',
            userAvatar: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=150&h=150&fit=crop',
            rating: 4.4,
            comment: 'Pleasant stay at this Riau boutique hotel. The location is superb for shopping and dining - Riau street offers endless options. Room is cozy with modern amenities including smart TV and good WiFi. Staff was friendly and accommodating with late check-out request. Bandung\'s cool climate is refreshing. Minor wear on some fixtures but overall well-maintained. Great value for central location. Perfect base for exploring Bandung\'s shopping scene and culinary offerings.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            propertyId: 90,
            carId: null,
            userId: null,
            userName: 'Ahmed Hassan',
            userAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&h=150&fit=crop',
            rating: 4.5,
            comment: 'Excellent boutique hotel in prime Riau location! Room is well-appointed with comfortable bed and modern bathroom. The location cannot be beaten - surrounded by Bandung\'s best shopping streets and restaurants. We loved the cool mountain weather that made walking around comfortable. Hotel staff provided great local recommendations and service was professional. Breakfast quality was good. Clean facilities and good maintenance. Highly recommend for shopping trips and city exploration.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.5,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },

        // Property 91: Family House in Setiabudhi, Bandung - 8 reviews (4.6-5.0 ratings)
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Michael Foster',
            userAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop',
            rating: 4.9,
            comment: 'Fantastic family house in Setiabudhi hills! The property is spacious and beautifully maintained with stunning views of Bandung city below. Setiabudhi area is upscale and peaceful - perfect for families. The cool mountain climate made our stay incredibly comfortable. Kids loved the garden area and the house has everything needed for a comfortable family vacation. Close to universities and restaurants. Host was exceptional with communication and local tips. Worth every rupiah for a luxury family getaway in Bandung.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.9,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Laura Schmidt',
            userAvatar: null,
            rating: 4.8,
            comment: 'Wonderful family home in prestigious Setiabudhi! The house is spacious with comfortable bedrooms and large living areas. Views overlooking Bandung are spectacular especially at sunset. The cool weather in the hills is refreshing - we didn\'t need air conditioning. Setiabudhi location offers peace while being close to city attractions. Kitchen is well-equipped and we enjoyed cooking family meals. Kids loved the outdoor space. Host provided excellent recommendations for family activities. Highly recommend for families!',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.7,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Robert Taylor',
            userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop',
            rating: 5.0,
            comment: 'Perfect family house in Setiabudhi hills! The property exceeded expectations with its size, amenities, and location. Bandung\'s cool mountain climate in this area is ideal - comfortable year-round. The views of the city from the house are breathtaking. Multiple bedrooms accommodated our large family comfortably. Setiabudhi neighborhood is safe and prestigious with good restaurants nearby. Host was responsive and provided detailed house information. Garden area was perfect for kids. Exceptional value for luxury family accommodation.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-08').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Catherine Liu',
            userAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop',
            rating: 4.7,
            comment: 'Beautiful family house in Setiabudhi! The property offers spacious accommodation with mountain views and cool climate. Setiabudhi area is upscale with great schools and restaurants nearby. House is well-maintained with modern kitchen and comfortable furniture. We enjoyed family dinners with city views. Kids loved exploring the garden. Bandung\'s pleasant weather made outdoor activities enjoyable. Host communication was clear and helpful. Minor issues with hot water but quickly resolved. Great for extended family stays.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.6,
            location: 4.8,
            value: 4.6,
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-10-05').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Daniel Anderson',
            userAvatar: null,
            rating: 4.9,
            comment: 'Excellent family house in premium Setiabudhi location! The property is spacious and beautifully furnished throughout. Views overlooking Bandung city are stunning from multiple rooms. Cool mountain climate of Setiabudhi hills is perfect - no heat, just fresh air. House has everything for comfortable family living including full kitchen and laundry. Neighborhood is safe and quiet. Close to universities and good restaurants. Host was professional and accommodating. Highly recommend for families seeking luxury and space.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.8,
            location: 4.9,
            value: 4.7,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-10-28').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Sophie Martin',
            userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop',
            rating: 4.6,
            comment: 'Great family accommodation in Setiabudhi hills. The house is large with plenty of space for everyone. Bandung\'s cool weather at this elevation is wonderful - perfect sleeping temperature. Views of the city are lovely especially at night. Setiabudhi area feels exclusive and secure. Kitchen facilities are good and we enjoyed home-cooked meals. Some furniture could use updating but overall very comfortable. Host was helpful with local information. Good value for spacious family house with views.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.5,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'William Chen',
            userAvatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=150&h=150&fit=crop',
            rating: 4.8,
            comment: 'Superb family house in Setiabudhi! Property offers generous space with modern amenities and beautiful city views. The cool climate of Bandung hills is refreshing and comfortable. Setiabudhi neighborhood is prestigious and quiet - great for families. House layout works perfectly for groups with private bedrooms and large common areas. Kitchen well-equipped for cooking. Garden provides outdoor space for kids. Host communication excellent with quick responses. Highly recommended for family gatherings or extended stays.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.8,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            propertyId: 91,
            carId: null,
            userId: null,
            userName: 'Elizabeth Brown',
            userAvatar: null,
            rating: 5.0,
            comment: 'Outstanding family house in Setiabudhi hills! The property is immaculate with luxury finishes throughout. Views overlooking Bandung are absolutely stunning - we spent hours on the terrace enjoying the scenery. Cool mountain climate is perfect year-round. Setiabudhi area is exclusive and safe with excellent restaurants and cafes nearby. House has every amenity imaginable including modern kitchen and quality furnishings. Kids loved the garden space. Host was exceptional with detailed information and support. Worth every penny for luxury family experience!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },

        // Property 92: Urban Condo in Pasteur, Bandung - 6 reviews (4.0-4.7 ratings)
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Kevin Zhang',
            userAvatar: 'https://images.unsplash.com/photo-1520785643438-5bf77931f493?w=150&h=150&fit=crop',
            rating: 4.5,
            comment: 'Great urban condo in Pasteur district! The location is excellent - close to hospitals, universities, and shopping areas. Condo is modern with good facilities including gym and pool. Bandung\'s cool climate makes the city living comfortable. Pasteur area has many restaurants and cafes within walking distance. Unit is clean and well-maintained with good WiFi. Host was responsive and check-in process smooth. Parking available. Good value for modern accommodation in convenient Bandung location.',
            cleanliness: 4.6,
            accuracy: 4.5,
            communication: 4.5,
            location: 4.7,
            value: 4.6,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Anna Kowalski',
            userAvatar: null,
            rating: 4.2,
            comment: 'Nice condo in Pasteur area. Unit is compact but efficiently designed for city living. Location is convenient with easy access to Pasteur attractions and main roads. Bandung\'s pleasant weather makes exploring comfortable. Building facilities are decent with working elevator and security. Some minor maintenance needed in unit but overall functional. Host communication was adequate. Good for short business trips or solo travelers. Reasonable price for central Pasteur location.',
            cleanliness: 4.3,
            accuracy: 4.2,
            communication: 4.1,
            location: 4.5,
            value: 4.3,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Ryan Murphy',
            userAvatar: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=150&h=150&fit=crop',
            rating: 4.6,
            comment: 'Excellent urban condo in Pasteur! The unit is modern and well-equipped with everything needed. Pasteur location is strategic - close to hospitals, shopping, and business areas. Building has good amenities and security. Bandung\'s cool climate is perfect for city living. We enjoyed exploring nearby cafes and restaurants. Condo is clean with comfortable furnishings. Host provided clear instructions and was helpful with recommendations. Parking secure. Great value for quality accommodation in prime Bandung location.',
            cleanliness: 4.7,
            accuracy: 4.6,
            communication: 4.6,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-10-18').toISOString(),
            updatedAt: new Date('2024-10-18').toISOString(),
        },
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Diana Silva',
            userAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop',
            rating: 4.3,
            comment: 'Solid condo in Pasteur district. The unit meets basic needs with clean space and working amenities. Pasteur area offers convenience with nearby restaurants and shopping. Bandung\'s cool weather is pleasant. Building maintenance could be better but condo itself is well-kept. WiFi works fine. Host was responsive to questions. Some noise from adjacent units but manageable. Fair pricing for location and facilities. Good option for practical accommodation in central Bandung.',
            cleanliness: 4.4,
            accuracy: 4.3,
            communication: 4.2,
            location: 4.6,
            value: 4.4,
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Patrick O\'Brien',
            userAvatar: null,
            rating: 4.7,
            comment: 'Very good urban condo in Pasteur! The unit is stylishly furnished with modern appliances and comfortable bed. Location is perfect - Pasteur district offers easy access to all parts of Bandung. Cool mountain climate makes city living enjoyable. Building facilities including pool and gym are well-maintained. We appreciated the security and parking. Host was excellent with communication and local tips. Condo exceeded expectations for cleanliness and comfort. Highly recommend for Bandung stays!',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.7,
            location: 4.8,
            value: 4.7,
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            propertyId: 92,
            carId: null,
            userId: null,
            userName: 'Lisa Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop',
            rating: 4.4,
            comment: 'Pleasant stay at Pasteur condo. Unit is modern with good layout and amenities. Pasteur location is convenient for business and leisure - close to hospitals and shopping centers. Bandung\'s cool climate is refreshing. Building has decent facilities and secure parking. Condo is clean with comfortable furnishings. Minor elevator delays during peak times. Host communication was good with helpful check-in instructions. Good value for quality urban accommodation in strategic Bandung location.',
            cleanliness: 4.5,
            accuracy: 4.4,
            communication: 4.3,
            location: 4.7,
            value: 4.5,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Bandung properties reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});