import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const now = new Date();
    const fourMonthsAgo = new Date(now.getTime() - 120 * 24 * 60 * 60 * 1000);
    
    const getRandomDate = (start: Date, end: Date) => {
        const startTime = start.getTime();
        const endTime = end.getTime();
        const randomTime = startTime + Math.random() * (endTime - startTime);
        return new Date(randomTime);
    };

    const sampleReviews = [
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'James Mitchell',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 5.0,
            comment: 'The location in Kuningan is perfect for business travelers. Walking distance to my office and plenty of restaurants nearby. The condo itself is modern and well-maintained. The rooftop pool has stunning city views!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.8,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), now).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), now).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Siti Nurhaliza',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 4.9,
            comment: 'Modern condo with amazing city views from the balcony. Loved waking up to the Jakarta skyline. The building amenities are top-notch - gym, pool, and 24-hour security. Highly recommend for couples or business trips.',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.9,
            createdAt: getRandomDate(new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'David Park',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.8,
            comment: 'Loved the building amenities especially the pool and gym. The condo is stylish with contemporary furniture and a fully equipped kitchen. Host was very responsive. Great location in the heart of Kuningan business district.',
            cleanliness: 4.8,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.7,
            createdAt: getRandomDate(new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Robert Chen',
            userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
            rating: 4.9,
            comment: 'Clean, stylish, and close to everything we needed. Walked to Kuningan City mall and numerous restaurants. The apartment is exactly as shown in photos. Very comfortable bed and powerful AC. Will definitely return!',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 4.8,
            location: 5.0,
            value: 4.8,
            createdAt: getRandomDate(new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Anita Wijaya',
            userAvatar: null,
            rating: 5.0,
            comment: 'Great place for couples, very romantic at night with the city lights. The living room is spacious and the smart TV was perfect for movie nights. Kitchen had everything we needed to cook breakfast.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.9,
            value: 5.0,
            createdAt: getRandomDate(new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Thomas Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
            rating: 4.7,
            comment: 'The kitchen was well-equipped for cooking. We prepared several meals during our stay. The condo is in excellent condition with modern appliances. Loved the building\'s facilities and the convenient location.',
            cleanliness: 4.8,
            accuracy: 4.7,
            communication: 4.6,
            location: 4.8,
            value: 4.7,
            createdAt: getRandomDate(new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 65 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 65 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Lisa Santoso',
            userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            rating: 4.9,
            comment: 'Perfect business stay in Kuningan. The work desk setup was ideal for remote work with fast WiFi. Close to major corporate offices. The building\'s executive lounge was a nice touch. Very professional environment.',
            cleanliness: 4.9,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.8,
            createdAt: getRandomDate(new Date(now.getTime() - 85 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 85 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Michael Rodriguez',
            userAvatar: null,
            rating: 5.0,
            comment: 'Absolutely loved our stay! The condo is beautifully decorated with attention to detail. The master bedroom is spacious with a comfortable king bed. Building security is excellent. Felt safe and comfortable throughout.',
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 5.0,
            value: 4.9,
            createdAt: getRandomDate(new Date(now.getTime() - 95 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 85 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 95 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 85 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Rachel Kim',
            userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
            rating: 4.8,
            comment: 'Amazing value for the location and quality. The condo exceeded our expectations. Clean, modern, and the view from the 25th floor is breathtaking. Easy access to malls, restaurants, and business centers.',
            cleanliness: 4.9,
            accuracy: 4.8,
            communication: 4.7,
            location: 5.0,
            value: 4.8,
            createdAt: getRandomDate(new Date(now.getTime() - 105 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 95 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 105 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 95 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 83,
            carId: null,
            userId: null,
            userName: 'Budi Hartono',
            userAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150',
            rating: 4.9,
            comment: 'Fantastic condo in prime Kuningan location. The interior design is chic and modern. All amenities worked perfectly. Host provided clear instructions for check-in. The rooftop pool at sunset is a must-experience!',
            cleanliness: 5.0,
            accuracy: 4.9,
            communication: 4.8,
            location: 5.0,
            value: 4.8,
            createdAt: getRandomDate(new Date(now.getTime() - 115 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 105 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: getRandomDate(new Date(now.getTime() - 115 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 105 * 24 * 60 * 60 * 1000)).toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder for property 83 completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});